/* t_yarp_generator::generate_service:3616 */
/*
 * SPDX-FileCopyrightText: 2006-2021 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: BSD-3-Clause
 */

// Autogenerated by Thrift Compiler (0.14.1-yarped)
//
// This is an automatically generated file.
// It could get re-generated if the ALLOW_IDL_GENERATION flag is on.

#ifndef YARP_THRIFT_GENERATOR_SERVICE_FAKEBATTERYSERVICE_H
#define YARP_THRIFT_GENERATOR_SERVICE_FAKEBATTERYSERVICE_H

#include <yarp/os/Wire.h>
#include <yarp/os/idl/WireTypes.h>
#include <yarp/dev/IBattery.h>

/* t_yarp_generator::generate_service:3712 */
class FakeBatteryService :
        public yarp::os::Wire
{
public:
/* t_yarp_generator::generate_service_constructor:4424 */
    // Constructor
    FakeBatteryService();

/* t_yarp_generator::generate_service_method:4449 */
    virtual void setBatteryVoltage(const double voltage);

/* t_yarp_generator::generate_service_method:4449 */
    virtual void setBatteryCurrent(const double current);

/* t_yarp_generator::generate_service_method:4449 */
    virtual void setBatteryCharge(const double charge);

/* t_yarp_generator::generate_service_method:4449 */
    virtual void setBatteryStatus(const yarp::dev::IBattery::Battery_status status);

/* t_yarp_generator::generate_service_method:4449 */
    virtual void setBatteryInfo(const std::string& info);

/* t_yarp_generator::generate_service_method:4449 */
    virtual void setBatteryTemperature(const double temperature);

/* t_yarp_generator::generate_service_method:4449 */
    virtual double getBatteryVoltage();

/* t_yarp_generator::generate_service_method:4449 */
    virtual double getBatteryCurrent();

/* t_yarp_generator::generate_service_method:4449 */
    virtual double getBatteryCharge();

/* t_yarp_generator::generate_service_method:4449 */
    virtual yarp::dev::IBattery::Battery_status getBatteryStatus();

/* t_yarp_generator::generate_service_method:4449 */
    virtual std::string getBatteryStatusString();

/* t_yarp_generator::generate_service_method:4449 */
    virtual std::string getBatteryInfo();

/* t_yarp_generator::generate_service_method:4449 */
    virtual double getBatteryTemperature();

/* t_yarp_generator::generate_service_help:4502 */
    // help method
    virtual std::vector<std::string> help(const std::string& functionName = "--all");

/* t_yarp_generator::generate_service_read:4584 */
    // read from ConnectionReader
    bool read(yarp::os::ConnectionReader& connection) override;
};

#endif // YARP_THRIFT_GENERATOR_SERVICE_FAKEBATTERYSERVICE_H
