/*
 * SPDX-FileCopyrightText: 2006-2021 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: BSD-3-Clause
 */

// Autogenerated by Thrift Compiler (0.14.1-yarped)
//
// This is an automatically generated file.
// It could get re-generated if the ALLOW_IDL_GENERATION flag is on.

#ifndef YARP_THRIFT_GENERATOR_STRUCT_AUDIOBUFFERSIZEDATASTORAGE_H
#define YARP_THRIFT_GENERATOR_STRUCT_AUDIOBUFFERSIZEDATASTORAGE_H

#include <yarp/dev/api.h>

#include <cstdint>
#include <cstdio>
#include <map>
#include <set>
#include <string>
#include <vector>

namespace yarp::dev {

class YARP_dev_API audioBufferSizeDataStorage
{
public:
    // Fields
    std::int32_t m_samples{0};
    std::int32_t m_channels{0};
    std::int32_t m_depth{0};
    std::int32_t size{0};

    // Default constructor
    audioBufferSizeDataStorage() = default;

    // Constructor with field values
    audioBufferSizeDataStorage(const std::int32_t m_samples,
                               const std::int32_t m_channels,
                               const std::int32_t m_depth,
                               const std::int32_t size);

};

} // namespace yarp::dev

#endif // YARP_THRIFT_GENERATOR_STRUCT_AUDIOBUFFERSIZEDATASTORAGE_H
