/*
 * SPDX-FileCopyrightText: 2006-2021 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: BSD-3-Clause
 */

// Autogenerated by Thrift Compiler (0.14.1-yarped)
//
// This is an automatically generated file.
// It could get re-generated if the ALLOW_IDL_GENERATION flag is on.

#include <yarp/dev/LaserScan2DStorage.h>

namespace yarp::dev {

// Constructor with field values
LaserScan2DStorage::LaserScan2DStorage(const double angle_min,
                                       const double angle_max,
                                       const double range_min,
                                       const double range_max,
                                       const std::vector<double>& scans,
                                       const std::int32_t status) :
        angle_min(angle_min),
        angle_max(angle_max),
        range_min(range_min),
        range_max(range_max),
        scans(scans),
        status(status)
{
}


} // namespace yarp::dev
