/*
 * SPDX-FileCopyrightText: 2006-2021 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: BSD-3-Clause
 */

// Autogenerated by Thrift Compiler (0.14.1-yarped)
//
// This is an automatically generated file.
// It could get re-generated if the ALLOW_IDL_GENERATION flag is on.

#ifndef YARP_THRIFT_GENERATOR_STRUCT_ODOMETRYDATA6DSTORAGE_H
#define YARP_THRIFT_GENERATOR_STRUCT_ODOMETRYDATA6DSTORAGE_H

#include <yarp/dev/api.h>

#include <cstdint>
#include <cstdio>
#include <map>
#include <set>
#include <string>
#include <vector>

namespace yarp::dev {

class YARP_dev_API OdometryData6DStorage
{
public:
    // Fields
    /**
     * position of the robot [m], expressed in the world reference frame
     */
    double odom_x{0.0};
    /**
     * position of the robot [m], expressed in the world reference frame
     */
    double odom_y{0.0};
    /**
     * position of the robot [m], expressed in the world reference frame
     */
    double odom_z{0.0};
    /**
     * orientation the robot [deg], expressed in the world reference frame
     */
    double odom_roll{0.0};
    /**
     * orientation the robot [deg], expressed in the world reference frame
     */
    double odom_pitch{0.0};
    /**
     * orientation the robot [deg], expressed in the world reference frame
     */
    double odom_yaw{0.0};
    /**
     * velocity of the robot [m/s] expressed in the robot reference frame
     */
    double base_vel_x{0.0};
    /**
     * velocity of the robot [m/s] expressed in the robot reference frame
     */
    double base_vel_y{0.0};
    /**
     * velocity of the robot [m/s] expressed in the robot reference frame
     */
    double base_vel_z{0.0};
    /**
     * angular velocity of the robot [deg/s] expressed in the robot reference frame
     */
    double base_vel_roll{0.0};
    /**
     * angular velocity of the robot [deg/s] expressed in the robot reference frame
     */
    double base_vel_pitch{0.0};
    /**
     * angular velocity of the robot [deg/s] expressed in the robot reference frame
     */
    double base_vel_yaw{0.0};
    /**
     * velocity of the robot [m/s] expressed in the world reference frame
     */
    double odom_vel_x{0.0};
    /**
     * velocity of the robot [m/s] expressed in the world reference frame
     */
    double odom_vel_y{0.0};
    /**
     * velocity of the robot [m/s] expressed in the world reference frame
     */
    double odom_vel_z{0.0};
    /**
     * angular velocity of the robot [deg/s] expressed in the world reference frame
     */
    double odom_vel_roll{0.0};
    /**
     * angular velocity of the robot [deg/s] expressed in the world reference frame
     */
    double odom_vel_pitch{0.0};
    /**
     * angular velocity of the robot [deg/s] expressed in the world reference frame
     */
    double odom_vel_yaw{0.0};

    // Default constructor
    OdometryData6DStorage() = default;

    // Constructor with field values
    OdometryData6DStorage(const double odom_x,
                          const double odom_y,
                          const double odom_z,
                          const double odom_roll,
                          const double odom_pitch,
                          const double odom_yaw,
                          const double base_vel_x,
                          const double base_vel_y,
                          const double base_vel_z,
                          const double base_vel_roll,
                          const double base_vel_pitch,
                          const double base_vel_yaw,
                          const double odom_vel_x,
                          const double odom_vel_y,
                          const double odom_vel_z,
                          const double odom_vel_roll,
                          const double odom_vel_pitch,
                          const double odom_vel_yaw);

};

} // namespace yarp::dev

#endif // YARP_THRIFT_GENERATOR_STRUCT_ODOMETRYDATA6DSTORAGE_H
