/*
 * SPDX-FileCopyrightText: 2006-2021 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: BSD-3-Clause
 */

// Autogenerated by Thrift Compiler (0.14.1-yarped)
//
// This is an automatically generated file.
// It could get re-generated if the ALLOW_IDL_GENERATION flag is on.

#include <yarp/dev/OdometryData6DStorage.h>

namespace yarp::dev {

// Constructor with field values
OdometryData6DStorage::OdometryData6DStorage(const double odom_x,
                                             const double odom_y,
                                             const double odom_z,
                                             const double odom_roll,
                                             const double odom_pitch,
                                             const double odom_yaw,
                                             const double base_vel_x,
                                             const double base_vel_y,
                                             const double base_vel_z,
                                             const double base_vel_roll,
                                             const double base_vel_pitch,
                                             const double base_vel_yaw,
                                             const double odom_vel_x,
                                             const double odom_vel_y,
                                             const double odom_vel_z,
                                             const double odom_vel_roll,
                                             const double odom_vel_pitch,
                                             const double odom_vel_yaw) :
        odom_x(odom_x),
        odom_y(odom_y),
        odom_z(odom_z),
        odom_roll(odom_roll),
        odom_pitch(odom_pitch),
        odom_yaw(odom_yaw),
        base_vel_x(base_vel_x),
        base_vel_y(base_vel_y),
        base_vel_z(base_vel_z),
        base_vel_roll(base_vel_roll),
        base_vel_pitch(base_vel_pitch),
        base_vel_yaw(base_vel_yaw),
        odom_vel_x(odom_vel_x),
        odom_vel_y(odom_vel_y),
        odom_vel_z(odom_vel_z),
        odom_vel_roll(odom_vel_roll),
        odom_vel_pitch(odom_vel_pitch),
        odom_vel_yaw(odom_vel_yaw)
{
}


} // namespace yarp::dev
