/* t_yarp_generator::generate_service:3616 */
/*
 * SPDX-FileCopyrightText: 2006-2021 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: BSD-3-Clause
 */

// Autogenerated by Thrift Compiler (0.14.1-yarped)
//
// This is an automatically generated file.
// It could get re-generated if the ALLOW_IDL_GENERATION flag is on.

#ifndef YARP_THRIFT_GENERATOR_SERVICE_YARPDATAPLAYER_CONSOLE_IDL_H
#define YARP_THRIFT_GENERATOR_SERVICE_YARPDATAPLAYER_CONSOLE_IDL_H

#include <yarp/os/Wire.h>
#include <yarp/os/idl/WireTypes.h>

/* t_yarp_generator::generate_service:3712 */
/**
 * yarpdataplayer_console_IDL
 * Interface.
 */
class yarpdataplayer_console_IDL :
        public yarp::os::Wire
{
public:
/* t_yarp_generator::generate_service_constructor:4424 */
    // Constructor
    yarpdataplayer_console_IDL();

/* t_yarp_generator::generate_service_method:4449 */
    /**
     * Steps the player once. The player will be stepped
     * until all parts have sent data
     * @return true/false on success/failure
     */
    virtual bool step();

/* t_yarp_generator::generate_service_method:4449 */
    /**
     * Sets the frame number to the user desired frame.
     * @param frameNum specifies the frame number the user
     *  would like to skip to
     * @return true/false on success/failure
     */
    virtual bool setFrame(const std::int32_t frameNum);

/* t_yarp_generator::generate_service_method:4449 */
    /**
     * Gets the frame number the user is requesting
     * @param name specifies the name of the data to modify
     *  would like to skip to
     * @return i32 returns the current frame index
     */
    virtual std::int32_t getFrame(const std::string& name);

/* t_yarp_generator::generate_service_method:4449 */
    /**
     * Loads a dataset from a path
     * @return true/false on success/failure
     */
    virtual bool load(const std::string& path);

/* t_yarp_generator::generate_service_method:4449 */
    /**
     * Plays the dataSets
     * @return true/false on success/failure
     */
    virtual bool play();

/* t_yarp_generator::generate_service_method:4449 */
    /**
     * Pauses the dataSets
     * @return true/false on success/failure
     */
    virtual bool pause();

/* t_yarp_generator::generate_service_method:4449 */
    /**
     * Stops the dataSets
     * @return true/false on success/failure
     */
    virtual bool stop();

/* t_yarp_generator::generate_service_method:4449 */
    /**
     * Enables the specified part.
     * @param name specifies the name of the loaded data
     * @return true/false on success/failure
     */
    virtual bool enable(const std::string& part);

/* t_yarp_generator::generate_service_method:4449 */
    /**
     * Disable the specified part.
     * @param name specifies the name of the loaded data
     * @return true/false on success/failure
     */
    virtual bool disable(const std::string& part);

/* t_yarp_generator::generate_service_method:4449 */
    /**
     * Gets the names of all parts loaded.
     * @return list of names of the loaded parts.
     */
    virtual std::vector<std::string> getAllParts();

/* t_yarp_generator::generate_service_method:4449 */
    /**
     * Gets the name of the port associated to the specified part
     * @param name specifies the name of the data to modify
     * @return port name
     */
    virtual std::string getPortName(const std::string& part);

/* t_yarp_generator::generate_service_method:4449 */
    /**
     * Sets the name of the port associated to the specified part
     * @param part specifies the name of the data to modify
     * @param new_name specifies the new name to assign to the port
     * @return true/false on success/failure
     */
    virtual bool setPortName(const std::string& part, const std::string& new_name);

/* t_yarp_generator::generate_service_method:4449 */
    /**
     * Sets the player speed
     * @param speed specifies
     * @return true/false on success/failure
     */
    virtual bool setSpeed(const double speed);

/* t_yarp_generator::generate_service_method:4449 */
    /**
     * Gets the player speed
     * @return value of the player speed
     */
    virtual double getSpeed();

/* t_yarp_generator::generate_service_method:4449 */
    /**
     * Sets repeat mode
     * @param val if true repeat mode is active.
     * @return true/false on success/failure
     */
    virtual bool repeat(const bool val = false);

/* t_yarp_generator::generate_service_method:4449 */
    /**
     * Sets strict mode
     * @param val if true strict mode is active.
     * @return true/false on success/failure
     */
    virtual bool setStrict(const bool val = false);

/* t_yarp_generator::generate_service_method:4449 */
    /**
     * Steps forward
     * @param steps number of steps to go forward (default=5).
     * @return true/false on success/failure
     */
    virtual bool forward(const std::int32_t steps = 5);

/* t_yarp_generator::generate_service_method:4449 */
    /**
     * Steps backward
     * @param steps number of steps to go backward (default=5).
     * @return true/false on success/failure
     */
    virtual bool backward(const std::int32_t steps = 5);

/* t_yarp_generator::generate_service_method:4449 */
    /**
     * Get the progress of the parts
     * @return the progress of the parts
     */
    virtual double getProgress();

/* t_yarp_generator::generate_service_method:4449 */
    /**
     * Get the status of playing
     * @return the status (playing, paused, stopped)
     */
    virtual std::string getStatus();

/* t_yarp_generator::generate_service_method:4449 */
    /**
     * Resume dataset from where it was paused
     * @return true/false on success/failure
     */
    virtual bool resume();

/* t_yarp_generator::generate_service_method:4449 */
    /**
     * Quit the module.
     * @return true/false on success/failure
     */
    virtual bool quit();

/* t_yarp_generator::generate_service_help:4502 */
    // help method
    virtual std::vector<std::string> help(const std::string& functionName = "--all");

/* t_yarp_generator::generate_service_read:4584 */
    // read from ConnectionReader
    bool read(yarp::os::ConnectionReader& connection) override;
};

#endif // YARP_THRIFT_GENERATOR_SERVICE_YARPDATAPLAYER_CONSOLE_IDL_H
