/* t_yarp_generator::generate_service:3762 */
/*
 * SPDX-FileCopyrightText: 2006-2021 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: BSD-3-Clause
 */

// Autogenerated by Thrift Compiler (0.14.1-yarped)
//
// This is an automatically generated file.
// It could get re-generated if the ALLOW_IDL_GENERATION flag is on.

#ifndef YARP_THRIFT_GENERATOR_SERVICE_MULTIPLEANALOGSENSORSMETADATA_H
#define YARP_THRIFT_GENERATOR_SERVICE_MULTIPLEANALOGSENSORSMETADATA_H

#include <yarp/os/Wire.h>
#include <yarp/os/idl/WireTypes.h>
#include <SensorRPCDataStorage.h>
#include <SensorRPCDataSerializer.h>

/* t_yarp_generator::generate_service:3858 */
class MultipleAnalogSensorsMetadata :
        public yarp::os::Wire
{
public:
/* t_yarp_generator::generate_service_constructor:4570 */
    // Constructor
    MultipleAnalogSensorsMetadata();

/* t_yarp_generator::generate_service_method:4595 */
    /**
     * Read the sensor metadata necessary to configure the MultipleAnalogSensorsClient device.
     */
    virtual SensorRPCDataStorage getMetadata();

/* t_yarp_generator::generate_service_help:4648 */
    // help method
    virtual std::vector<std::string> help(const std::string& functionName = "--all");

/* t_yarp_generator::generate_service_read:4730 */
    // read from ConnectionReader
    bool read(yarp::os::ConnectionReader& connection) override;
};

#endif // YARP_THRIFT_GENERATOR_SERVICE_MULTIPLEANALOGSENSORSMETADATA_H
