/* t_yarp_generator::generate_service:3617 */
/*
 * SPDX-FileCopyrightText: 2006-2021 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: BSD-3-Clause
 */

// Autogenerated by Thrift Compiler (0.14.1-yarped)
//
// This is an automatically generated file.
// It could get re-generated if the ALLOW_IDL_GENERATION flag is on.

#include <MultipleAnalogSensorsMetadata.h>

#include <yarp/os/idl/WireTypes.h>

#include <algorithm>

/* t_yarp_generator::generate_service:3713 */
/* t_yarp_generator::generate_service_helper_classes:3761 */
/* t_yarp_generator::generate_service_helper_classes_decl:3778 */
// getMetadata helper class declaration
class MultipleAnalogSensorsMetadata_getMetadata_helper :
        public yarp::os::Portable
{
public:
    MultipleAnalogSensorsMetadata_getMetadata_helper() = default;
    bool write(yarp::os::ConnectionWriter& connection) const override;
    bool read(yarp::os::ConnectionReader& connection) override;

    class Command :
            public yarp::os::idl::WirePortable
    {
    public:
        Command() = default;
        ~Command() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool writeTag(const yarp::os::idl::WireWriter& writer) const;
        bool writeArgs(const yarp::os::idl::WireWriter& writer) const;

        bool read(yarp::os::idl::WireReader& reader) override;
        bool readTag(yarp::os::idl::WireReader& reader);
        bool readArgs(yarp::os::idl::WireReader& reader);
    };

    class Reply :
            public yarp::os::idl::WirePortable
    {
    public:
        Reply() = default;
        ~Reply() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool read(yarp::os::idl::WireReader& reader) override;

        SensorRPCDataStorage return_helper{};
    };

    using funcptr_t = SensorRPCDataStorage (*)();
    void call(MultipleAnalogSensorsMetadata* ptr);

    Command cmd;
    Reply reply;

    static constexpr const char* s_tag{"getMetadata"};
    static constexpr size_t s_tag_len{1};
    static constexpr size_t s_cmd_len{1};
    static constexpr size_t s_reply_len{10};
    static constexpr const char* s_prototype{"SensorRPCDataStorage MultipleAnalogSensorsMetadata::getMetadata()"};
    static constexpr const char* s_help{
        "Read the sensor metadata necessary to configure the MultipleAnalogSensorsClient device."
    };
};

/* t_yarp_generator::generate_service_helper_classes_impl:3924 */
// getMetadata helper class implementation
/* t_yarp_generator::generate_service_helper_classes_impl_write:3990 */
bool MultipleAnalogSensorsMetadata_getMetadata_helper::write(yarp::os::ConnectionWriter& connection) const
{
    return cmd.write(connection);
}

/* t_yarp_generator::generate_service_helper_classes_impl_read:4038 */
bool MultipleAnalogSensorsMetadata_getMetadata_helper::read(yarp::os::ConnectionReader& connection)
{
    return reply.read(connection);
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_write_connectionwriter:4058 */
bool MultipleAnalogSensorsMetadata_getMetadata_helper::Command::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    if (!writer.writeListHeader(s_cmd_len)) {
        return false;
    }
    return write(writer);
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_read_connectionreader:4080 */
bool MultipleAnalogSensorsMetadata_getMetadata_helper::Command::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    if (!reader.readListHeader()) {
        reader.fail();
        return false;
    }
    return read(reader);
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_write_wirewriter:4110 */
bool MultipleAnalogSensorsMetadata_getMetadata_helper::Command::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writeTag(writer)) {
        return false;
    }
    if (!writeArgs(writer)) {
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_writetag:4132 */
bool MultipleAnalogSensorsMetadata_getMetadata_helper::Command::writeTag(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeTag(s_tag, 1, s_tag_len)) {
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_writeargs:4153 */
bool MultipleAnalogSensorsMetadata_getMetadata_helper::Command::writeArgs(const yarp::os::idl::WireWriter& writer [[maybe_unused]]) const
{
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_read_wirereader:4181 */
bool MultipleAnalogSensorsMetadata_getMetadata_helper::Command::read(yarp::os::idl::WireReader& reader)
{
    if (!readTag(reader)) {
        return false;
    }
    if (!readArgs(reader)) {
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_readtag:4201 */
bool MultipleAnalogSensorsMetadata_getMetadata_helper::Command::readTag(yarp::os::idl::WireReader& reader)
{
    std::string tag = reader.readTag(s_tag_len);
    if (reader.isError()) {
        return false;
    }
    if (tag != s_tag) {
        reader.fail();
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_readargs:4229 */
bool MultipleAnalogSensorsMetadata_getMetadata_helper::Command::readArgs(yarp::os::idl::WireReader& reader)
{
    if (!reader.noMore()) {
        reader.fail();
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_reply_write_connectionwriter:4259 */
bool MultipleAnalogSensorsMetadata_getMetadata_helper::Reply::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    return write(writer);
}

/* t_yarp_generator::generate_service_helper_classes_impl_reply_read_connectionreader:4280 */
bool MultipleAnalogSensorsMetadata_getMetadata_helper::Reply::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    return read(reader);
}

/* t_yarp_generator::generate_service_helper_classes_impl_reply_write_wirewriter:4301 */
bool MultipleAnalogSensorsMetadata_getMetadata_helper::Reply::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.isNull()) {
        if (!writer.writeListHeader(s_reply_len)) {
            return false;
        }
/* t_yarp_generator::generate_serialize_field:1093 */
/* t_yarp_generator::generate_serialize_struct:1215 */
        const SensorRPCDataSerializer tmp_SensorRPCDataSerializer(return_helper);
        if (!writer.write(tmp_SensorRPCDataSerializer)) {
            return false;
        }
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_reply_read_wirereader:4347 */
bool MultipleAnalogSensorsMetadata_getMetadata_helper::Reply::read(yarp::os::idl::WireReader& reader)
{
    if (!reader.readListReturn()) {
        return false;
    }
/* t_yarp_generator::generate_deserialize_field:1361 */
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
/* t_yarp_generator::generate_deserialize_struct:1516 */
    SensorRPCDataSerializer tmp_SensorRPCDataSerializer(return_helper);
    if (!reader.read(tmp_SensorRPCDataSerializer)) {
/* t_yarp_generator::generate_deserialize_field_fallback:1344 */
        reader.fail();
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_call:4385 */
void MultipleAnalogSensorsMetadata_getMetadata_helper::call(MultipleAnalogSensorsMetadata* ptr)
{
    reply.return_helper = ptr->getMetadata();
}

/* t_yarp_generator::generate_service_constructor:4425 */
// Constructor
MultipleAnalogSensorsMetadata::MultipleAnalogSensorsMetadata()
{
    yarp().setOwner(*this);
}

/* t_yarp_generator::generate_service_method:4450 */
SensorRPCDataStorage MultipleAnalogSensorsMetadata::getMetadata()
{
    if (!yarp().canWrite()) {
        yError("Missing server method '%s'?", MultipleAnalogSensorsMetadata_getMetadata_helper::s_prototype);
    }
    MultipleAnalogSensorsMetadata_getMetadata_helper helper{};
    bool ok = yarp().write(helper, helper);
    return ok ? helper.reply.return_helper : SensorRPCDataStorage{};
}

/* t_yarp_generator::generate_service_help:4503 */
// help method
std::vector<std::string> MultipleAnalogSensorsMetadata::help(const std::string& functionName)
{
    bool showAll = (functionName == "--all");
    std::vector<std::string> helpString;
    if (showAll) {
        helpString.emplace_back("*** Available commands:");
        helpString.emplace_back(MultipleAnalogSensorsMetadata_getMetadata_helper::s_tag);
        helpString.emplace_back("help");
    } else {
        if (functionName == MultipleAnalogSensorsMetadata_getMetadata_helper::s_tag) {
            helpString.emplace_back(MultipleAnalogSensorsMetadata_getMetadata_helper::s_prototype);
            helpString.emplace_back(MultipleAnalogSensorsMetadata_getMetadata_helper::s_help);
        }
        if (functionName == "help") {
            helpString.emplace_back("std::vector<std::string> help(const std::string& functionName = \"--all\")");
            helpString.emplace_back("Return list of available commands, or help message for a specific function");
            helpString.emplace_back("@param functionName name of command for which to get a detailed description. If none or '--all' is provided, print list of available commands");
            helpString.emplace_back("@return list of strings (one string per line)");
        }
    }
    if (helpString.empty()) {
        helpString.emplace_back("Command not found");
    }
    return helpString;
}

/* t_yarp_generator::generate_service_read:4585 */
// read from ConnectionReader
bool MultipleAnalogSensorsMetadata::read(yarp::os::ConnectionReader& connection)
{
    constexpr size_t max_tag_len = 1;
    size_t tag_len = 1;

    yarp::os::idl::WireReader reader(connection);
    reader.expectAccept();
    if (!reader.readListHeader()) {
        reader.fail();
        return false;
    }

    std::string tag = reader.readTag(1);
    bool direct = (tag == "__direct__");
    if (direct) {
        tag = reader.readTag(1);
    }
    while (tag_len <= max_tag_len && !reader.isError()) {
        if (tag == MultipleAnalogSensorsMetadata_getMetadata_helper::s_tag) {
            MultipleAnalogSensorsMetadata_getMetadata_helper helper;
            if (!helper.cmd.readArgs(reader)) {
                return false;
            }

            helper.call(this);

            yarp::os::idl::WireWriter writer(reader);
            if (!helper.reply.write(writer)) {
                return false;
            }
            reader.accept();
            return true;
        }
        if (tag == "help") {
            std::string functionName;
            if (!reader.readString(functionName)) {
                functionName = "--all";
            }
            auto help_strings = help(functionName);
            yarp::os::idl::WireWriter writer(reader);
            if (!writer.isNull()) {
                if (!writer.writeListHeader(2)) {
                    return false;
                }
                if (!writer.writeTag("many", 1, 0)) {
                    return false;
                }
                if (!writer.writeListBegin(0, help_strings.size())) {
                    return false;
                }
                for (const auto& help_string : help_strings) {
                    if (!writer.writeString(help_string)) {
                        return false;
                    }
                }
                if (!writer.writeListEnd()) {
                    return false;
                }
            }
            reader.accept();
            return true;
        }
        if (reader.noMore()) {
            reader.fail();
            return false;
        }
        std::string next_tag = reader.readTag(1);
        if (next_tag.empty()) {
            break;
        }
        tag.append("_").append(next_tag);
        tag_len = std::count(tag.begin(), tag.end(), '_') + 1;
    }
    return false;
}
