/* t_yarp_generator::generate_service:3616 */
/*
 * SPDX-FileCopyrightText: 2006-2021 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: BSD-3-Clause
 */

// Autogenerated by Thrift Compiler (0.14.1-yarped)
//
// This is an automatically generated file.
// It could get re-generated if the ALLOW_IDL_GENERATION flag is on.

#ifndef YARP_THRIFT_GENERATOR_SERVICE_FRAMETRANSFORMSTORAGEGETRPC_H
#define YARP_THRIFT_GENERATOR_SERVICE_FRAMETRANSFORMSTORAGEGETRPC_H

#include <yarp/os/Wire.h>
#include <yarp/os/idl/WireTypes.h>
#include <return_getAllTransformsStorage.h>
#include <return_getAllTransformsSerializer.h>

/* t_yarp_generator::generate_service:3712 */
class FrameTransformStorageGetRPC :
        public yarp::os::Wire
{
public:
/* t_yarp_generator::generate_service_constructor:4424 */
    // Constructor
    FrameTransformStorageGetRPC();

/* t_yarp_generator::generate_service_method:4449 */
    virtual return_getAllTransformsStorage getTransformsRPC();

/* t_yarp_generator::generate_service_help:4502 */
    // help method
    virtual std::vector<std::string> help(const std::string& functionName = "--all");

/* t_yarp_generator::generate_service_read:4584 */
    // read from ConnectionReader
    bool read(yarp::os::ConnectionReader& connection) override;
};

#endif // YARP_THRIFT_GENERATOR_SERVICE_FRAMETRANSFORMSTORAGEGETRPC_H
