/* t_yarp_generator::generate_service:3763 */
/*
 * SPDX-FileCopyrightText: 2006-2021 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: BSD-3-Clause
 */

// Autogenerated by Thrift Compiler (0.14.1-yarped)
//
// This is an automatically generated file.
// It could get re-generated if the ALLOW_IDL_GENERATION flag is on.

#include <yarpdataplayer_IDL.h>

#include <yarp/os/idl/WireTypes.h>

#include <algorithm>

/* t_yarp_generator::generate_service:3859 */
/* t_yarp_generator::generate_service_helper_classes:3907 */
/* t_yarp_generator::generate_service_helper_classes_decl:3924 */
// step helper class declaration
class yarpdataplayer_IDL_step_helper :
        public yarp::os::Portable
{
public:
    yarpdataplayer_IDL_step_helper() = default;
    bool write(yarp::os::ConnectionWriter& connection) const override;
    bool read(yarp::os::ConnectionReader& connection) override;

    class Command :
            public yarp::os::idl::WirePortable
    {
    public:
        Command() = default;
        ~Command() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool writeTag(const yarp::os::idl::WireWriter& writer) const;
        bool writeArgs(const yarp::os::idl::WireWriter& writer) const;

        bool read(yarp::os::idl::WireReader& reader) override;
        bool readTag(yarp::os::idl::WireReader& reader);
        bool readArgs(yarp::os::idl::WireReader& reader);
    };

    class Reply :
            public yarp::os::idl::WirePortable
    {
    public:
        Reply() = default;
        ~Reply() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool read(yarp::os::idl::WireReader& reader) override;

        bool return_helper{false};
    };

    using funcptr_t = bool (*)();
    void call(yarpdataplayer_IDL* ptr);

    Command cmd;
    Reply reply;

    static constexpr const char* s_tag{"step"};
    static constexpr size_t s_tag_len{1};
    static constexpr size_t s_cmd_len{1};
    static constexpr size_t s_reply_len{1};
    static constexpr const char* s_prototype{"bool yarpdataplayer_IDL::step()"};
    static constexpr const char* s_help{
        "Steps the player once. The player will be stepped\n"
        "until all parts have sent data\n"
        "@return true/false on success/failure"
    };
};

/* t_yarp_generator::generate_service_helper_classes_decl:3924 */
// setFrame helper class declaration
class yarpdataplayer_IDL_setFrame_helper :
        public yarp::os::Portable
{
public:
    yarpdataplayer_IDL_setFrame_helper() = default;
    explicit yarpdataplayer_IDL_setFrame_helper(const std::int32_t frameNum);
    bool write(yarp::os::ConnectionWriter& connection) const override;
    bool read(yarp::os::ConnectionReader& connection) override;

    class Command :
            public yarp::os::idl::WirePortable
    {
    public:
        Command() = default;
        explicit Command(const std::int32_t frameNum);

        ~Command() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool writeTag(const yarp::os::idl::WireWriter& writer) const;
        bool writeArgs(const yarp::os::idl::WireWriter& writer) const;

        bool read(yarp::os::idl::WireReader& reader) override;
        bool readTag(yarp::os::idl::WireReader& reader);
        bool readArgs(yarp::os::idl::WireReader& reader);

        std::int32_t frameNum{0};
    };

    class Reply :
            public yarp::os::idl::WirePortable
    {
    public:
        Reply() = default;
        ~Reply() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool read(yarp::os::idl::WireReader& reader) override;

        bool return_helper{false};
    };

    using funcptr_t = bool (*)(const std::int32_t);
    void call(yarpdataplayer_IDL* ptr);

    Command cmd;
    Reply reply;

    static constexpr const char* s_tag{"setFrame"};
    static constexpr size_t s_tag_len{1};
    static constexpr size_t s_cmd_len{2};
    static constexpr size_t s_reply_len{1};
    static constexpr const char* s_prototype{"bool yarpdataplayer_IDL::setFrame(const std::int32_t frameNum)"};
    static constexpr const char* s_help{
        "Sets the frame number to the user desired frame.\n"
        "@param frameNum specifies the frame number the user\n"
        " would like to skip to\n"
        "@return true/false on success/failure"
    };
};

/* t_yarp_generator::generate_service_helper_classes_decl:3924 */
// getFrame helper class declaration
class yarpdataplayer_IDL_getFrame_helper :
        public yarp::os::Portable
{
public:
    yarpdataplayer_IDL_getFrame_helper() = default;
    explicit yarpdataplayer_IDL_getFrame_helper(const std::string& name);
    bool write(yarp::os::ConnectionWriter& connection) const override;
    bool read(yarp::os::ConnectionReader& connection) override;

    class Command :
            public yarp::os::idl::WirePortable
    {
    public:
        Command() = default;
        explicit Command(const std::string& name);

        ~Command() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool writeTag(const yarp::os::idl::WireWriter& writer) const;
        bool writeArgs(const yarp::os::idl::WireWriter& writer) const;

        bool read(yarp::os::idl::WireReader& reader) override;
        bool readTag(yarp::os::idl::WireReader& reader);
        bool readArgs(yarp::os::idl::WireReader& reader);

        std::string name{};
    };

    class Reply :
            public yarp::os::idl::WirePortable
    {
    public:
        Reply() = default;
        ~Reply() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool read(yarp::os::idl::WireReader& reader) override;

        std::int32_t return_helper{0};
    };

    using funcptr_t = std::int32_t (*)(const std::string&);
    void call(yarpdataplayer_IDL* ptr);

    Command cmd;
    Reply reply;

    static constexpr const char* s_tag{"getFrame"};
    static constexpr size_t s_tag_len{1};
    static constexpr size_t s_cmd_len{2};
    static constexpr size_t s_reply_len{1};
    static constexpr const char* s_prototype{"std::int32_t yarpdataplayer_IDL::getFrame(const std::string& name)"};
    static constexpr const char* s_help{
        "Gets the frame number the user is requesting\n"
        "@param name specifies the name of the data to modify\n"
        " would like to skip to\n"
        "@return i32 returns the current frame index"
    };
};

/* t_yarp_generator::generate_service_helper_classes_decl:3924 */
// load helper class declaration
class yarpdataplayer_IDL_load_helper :
        public yarp::os::Portable
{
public:
    yarpdataplayer_IDL_load_helper() = default;
    explicit yarpdataplayer_IDL_load_helper(const std::string& path);
    bool write(yarp::os::ConnectionWriter& connection) const override;
    bool read(yarp::os::ConnectionReader& connection) override;

    class Command :
            public yarp::os::idl::WirePortable
    {
    public:
        Command() = default;
        explicit Command(const std::string& path);

        ~Command() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool writeTag(const yarp::os::idl::WireWriter& writer) const;
        bool writeArgs(const yarp::os::idl::WireWriter& writer) const;

        bool read(yarp::os::idl::WireReader& reader) override;
        bool readTag(yarp::os::idl::WireReader& reader);
        bool readArgs(yarp::os::idl::WireReader& reader);

        std::string path{};
    };

    class Reply :
            public yarp::os::idl::WirePortable
    {
    public:
        Reply() = default;
        ~Reply() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool read(yarp::os::idl::WireReader& reader) override;

        bool return_helper{false};
    };

    using funcptr_t = bool (*)(const std::string&);
    void call(yarpdataplayer_IDL* ptr);

    Command cmd;
    Reply reply;

    static constexpr const char* s_tag{"load"};
    static constexpr size_t s_tag_len{1};
    static constexpr size_t s_cmd_len{2};
    static constexpr size_t s_reply_len{1};
    static constexpr const char* s_prototype{"bool yarpdataplayer_IDL::load(const std::string& path)"};
    static constexpr const char* s_help{
        "Loads a dataset from a path\n"
        "@return true/false on success/failure"
    };
};

/* t_yarp_generator::generate_service_helper_classes_decl:3924 */
// getSliderPercentage helper class declaration
class yarpdataplayer_IDL_getSliderPercentage_helper :
        public yarp::os::Portable
{
public:
    yarpdataplayer_IDL_getSliderPercentage_helper() = default;
    bool write(yarp::os::ConnectionWriter& connection) const override;
    bool read(yarp::os::ConnectionReader& connection) override;

    class Command :
            public yarp::os::idl::WirePortable
    {
    public:
        Command() = default;
        ~Command() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool writeTag(const yarp::os::idl::WireWriter& writer) const;
        bool writeArgs(const yarp::os::idl::WireWriter& writer) const;

        bool read(yarp::os::idl::WireReader& reader) override;
        bool readTag(yarp::os::idl::WireReader& reader);
        bool readArgs(yarp::os::idl::WireReader& reader);
    };

    class Reply :
            public yarp::os::idl::WirePortable
    {
    public:
        Reply() = default;
        ~Reply() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool read(yarp::os::idl::WireReader& reader) override;

        std::int32_t return_helper{0};
    };

    using funcptr_t = std::int32_t (*)();
    void call(yarpdataplayer_IDL* ptr);

    Command cmd;
    Reply reply;

    static constexpr const char* s_tag{"getSliderPercentage"};
    static constexpr size_t s_tag_len{1};
    static constexpr size_t s_cmd_len{1};
    static constexpr size_t s_reply_len{1};
    static constexpr const char* s_prototype{"std::int32_t yarpdataplayer_IDL::getSliderPercentage()"};
    static constexpr const char* s_help{
        "Get slider percentage\n"
        "@return i32 percentage"
    };
};

/* t_yarp_generator::generate_service_helper_classes_decl:3924 */
// getStatus helper class declaration
class yarpdataplayer_IDL_getStatus_helper :
        public yarp::os::Portable
{
public:
    yarpdataplayer_IDL_getStatus_helper() = default;
    bool write(yarp::os::ConnectionWriter& connection) const override;
    bool read(yarp::os::ConnectionReader& connection) override;

    class Command :
            public yarp::os::idl::WirePortable
    {
    public:
        Command() = default;
        ~Command() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool writeTag(const yarp::os::idl::WireWriter& writer) const;
        bool writeArgs(const yarp::os::idl::WireWriter& writer) const;

        bool read(yarp::os::idl::WireReader& reader) override;
        bool readTag(yarp::os::idl::WireReader& reader);
        bool readArgs(yarp::os::idl::WireReader& reader);
    };

    class Reply :
            public yarp::os::idl::WirePortable
    {
    public:
        Reply() = default;
        ~Reply() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool read(yarp::os::idl::WireReader& reader) override;

        std::string return_helper{};
    };

    using funcptr_t = std::string (*)();
    void call(yarpdataplayer_IDL* ptr);

    Command cmd;
    Reply reply;

    static constexpr const char* s_tag{"getStatus"};
    static constexpr size_t s_tag_len{1};
    static constexpr size_t s_cmd_len{1};
    static constexpr size_t s_reply_len{1};
    static constexpr const char* s_prototype{"std::string yarpdataplayer_IDL::getStatus()"};
    static constexpr const char* s_help{
        "Get the status of playing\n"
        "@return the status (playing, paused, stopped)"
    };
};

/* t_yarp_generator::generate_service_helper_classes_decl:3924 */
// play helper class declaration
class yarpdataplayer_IDL_play_helper :
        public yarp::os::Portable
{
public:
    yarpdataplayer_IDL_play_helper() = default;
    bool write(yarp::os::ConnectionWriter& connection) const override;
    bool read(yarp::os::ConnectionReader& connection) override;

    class Command :
            public yarp::os::idl::WirePortable
    {
    public:
        Command() = default;
        ~Command() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool writeTag(const yarp::os::idl::WireWriter& writer) const;
        bool writeArgs(const yarp::os::idl::WireWriter& writer) const;

        bool read(yarp::os::idl::WireReader& reader) override;
        bool readTag(yarp::os::idl::WireReader& reader);
        bool readArgs(yarp::os::idl::WireReader& reader);
    };

    class Reply :
            public yarp::os::idl::WirePortable
    {
    public:
        Reply() = default;
        ~Reply() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool read(yarp::os::idl::WireReader& reader) override;

        bool return_helper{false};
    };

    using funcptr_t = bool (*)();
    void call(yarpdataplayer_IDL* ptr);

    Command cmd;
    Reply reply;

    static constexpr const char* s_tag{"play"};
    static constexpr size_t s_tag_len{1};
    static constexpr size_t s_cmd_len{1};
    static constexpr size_t s_reply_len{1};
    static constexpr const char* s_prototype{"bool yarpdataplayer_IDL::play()"};
    static constexpr const char* s_help{
        "Plays the dataSets\n"
        "@return true/false on success/failure"
    };
};

/* t_yarp_generator::generate_service_helper_classes_decl:3924 */
// pause helper class declaration
class yarpdataplayer_IDL_pause_helper :
        public yarp::os::Portable
{
public:
    yarpdataplayer_IDL_pause_helper() = default;
    bool write(yarp::os::ConnectionWriter& connection) const override;
    bool read(yarp::os::ConnectionReader& connection) override;

    class Command :
            public yarp::os::idl::WirePortable
    {
    public:
        Command() = default;
        ~Command() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool writeTag(const yarp::os::idl::WireWriter& writer) const;
        bool writeArgs(const yarp::os::idl::WireWriter& writer) const;

        bool read(yarp::os::idl::WireReader& reader) override;
        bool readTag(yarp::os::idl::WireReader& reader);
        bool readArgs(yarp::os::idl::WireReader& reader);
    };

    class Reply :
            public yarp::os::idl::WirePortable
    {
    public:
        Reply() = default;
        ~Reply() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool read(yarp::os::idl::WireReader& reader) override;

        bool return_helper{false};
    };

    using funcptr_t = bool (*)();
    void call(yarpdataplayer_IDL* ptr);

    Command cmd;
    Reply reply;

    static constexpr const char* s_tag{"pause"};
    static constexpr size_t s_tag_len{1};
    static constexpr size_t s_cmd_len{1};
    static constexpr size_t s_reply_len{1};
    static constexpr const char* s_prototype{"bool yarpdataplayer_IDL::pause()"};
    static constexpr const char* s_help{
        "Pauses the dataSets\n"
        "@return true/false on success/failure"
    };
};

/* t_yarp_generator::generate_service_helper_classes_decl:3924 */
// stop helper class declaration
class yarpdataplayer_IDL_stop_helper :
        public yarp::os::Portable
{
public:
    yarpdataplayer_IDL_stop_helper() = default;
    bool write(yarp::os::ConnectionWriter& connection) const override;
    bool read(yarp::os::ConnectionReader& connection) override;

    class Command :
            public yarp::os::idl::WirePortable
    {
    public:
        Command() = default;
        ~Command() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool writeTag(const yarp::os::idl::WireWriter& writer) const;
        bool writeArgs(const yarp::os::idl::WireWriter& writer) const;

        bool read(yarp::os::idl::WireReader& reader) override;
        bool readTag(yarp::os::idl::WireReader& reader);
        bool readArgs(yarp::os::idl::WireReader& reader);
    };

    class Reply :
            public yarp::os::idl::WirePortable
    {
    public:
        Reply() = default;
        ~Reply() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool read(yarp::os::idl::WireReader& reader) override;

        bool return_helper{false};
    };

    using funcptr_t = bool (*)();
    void call(yarpdataplayer_IDL* ptr);

    Command cmd;
    Reply reply;

    static constexpr const char* s_tag{"stop"};
    static constexpr size_t s_tag_len{1};
    static constexpr size_t s_cmd_len{1};
    static constexpr size_t s_reply_len{1};
    static constexpr const char* s_prototype{"bool yarpdataplayer_IDL::stop()"};
    static constexpr const char* s_help{
        "Stops the dataSets\n"
        "@return true/false on success/failure"
    };
};

/* t_yarp_generator::generate_service_helper_classes_decl:3924 */
// quit helper class declaration
class yarpdataplayer_IDL_quit_helper :
        public yarp::os::Portable
{
public:
    yarpdataplayer_IDL_quit_helper() = default;
    bool write(yarp::os::ConnectionWriter& connection) const override;
    bool read(yarp::os::ConnectionReader& connection) override;

    class Command :
            public yarp::os::idl::WirePortable
    {
    public:
        Command() = default;
        ~Command() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool writeTag(const yarp::os::idl::WireWriter& writer) const;
        bool writeArgs(const yarp::os::idl::WireWriter& writer) const;

        bool read(yarp::os::idl::WireReader& reader) override;
        bool readTag(yarp::os::idl::WireReader& reader);
        bool readArgs(yarp::os::idl::WireReader& reader);
    };

    class Reply :
            public yarp::os::idl::WirePortable
    {
    public:
        Reply() = default;
        ~Reply() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool read(yarp::os::idl::WireReader& reader) override;

        bool return_helper{false};
    };

    using funcptr_t = bool (*)();
    void call(yarpdataplayer_IDL* ptr);

    Command cmd;
    Reply reply;

    static constexpr const char* s_tag{"quit"};
    static constexpr size_t s_tag_len{1};
    static constexpr size_t s_cmd_len{1};
    static constexpr size_t s_reply_len{1};
    static constexpr const char* s_prototype{"bool yarpdataplayer_IDL::quit()"};
    static constexpr const char* s_help{
        "Quit the module.\n"
        "@return true/false on success/failure"
    };
};

/* t_yarp_generator::generate_service_helper_classes_impl:4070 */
// step helper class implementation
/* t_yarp_generator::generate_service_helper_classes_impl_write:4136 */
bool yarpdataplayer_IDL_step_helper::write(yarp::os::ConnectionWriter& connection) const
{
    return cmd.write(connection);
}

/* t_yarp_generator::generate_service_helper_classes_impl_read:4184 */
bool yarpdataplayer_IDL_step_helper::read(yarp::os::ConnectionReader& connection)
{
    return reply.read(connection);
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_write_connectionwriter:4204 */
bool yarpdataplayer_IDL_step_helper::Command::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    if (!writer.writeListHeader(s_cmd_len)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    return write(writer);
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_read_connectionreader:4226 */
bool yarpdataplayer_IDL_step_helper::Command::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    if (!reader.readListHeader()) {
        reader.fail();
        return false;
    }
    return read(reader);
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_write_wirewriter:4256 */
bool yarpdataplayer_IDL_step_helper::Command::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writeTag(writer)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    if (!writeArgs(writer)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_writetag:4278 */
bool yarpdataplayer_IDL_step_helper::Command::writeTag(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeTag(s_tag, 1, s_tag_len)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_writeargs:4299 */
bool yarpdataplayer_IDL_step_helper::Command::writeArgs(const yarp::os::idl::WireWriter& writer [[maybe_unused]]) const
{
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_read_wirereader:4327 */
bool yarpdataplayer_IDL_step_helper::Command::read(yarp::os::idl::WireReader& reader)
{
    if (!readTag(reader)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    if (!readArgs(reader)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_readtag:4347 */
bool yarpdataplayer_IDL_step_helper::Command::readTag(yarp::os::idl::WireReader& reader)
{
    std::string tag = reader.readTag(s_tag_len);
    if (reader.isError()) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    if (tag != s_tag) {
        reader.fail();
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_readargs:4375 */
bool yarpdataplayer_IDL_step_helper::Command::readArgs(yarp::os::idl::WireReader& reader)
{
    if (!reader.noMore()) {
        reader.fail();
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_reply_write_connectionwriter:4405 */
bool yarpdataplayer_IDL_step_helper::Reply::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    return write(writer);
}

/* t_yarp_generator::generate_service_helper_classes_impl_reply_read_connectionreader:4426 */
bool yarpdataplayer_IDL_step_helper::Reply::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    return read(reader);
}

/* t_yarp_generator::generate_service_helper_classes_impl_reply_write_wirewriter:4447 */
bool yarpdataplayer_IDL_step_helper::Reply::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.isNull()) {
        if (!writer.writeListHeader(s_reply_len)) {
            yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
            return false;
        }
/* t_yarp_generator::generate_serialize_field:1146 */
        if (!writer.writeBool(return_helper)) {
            yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
            return false;
        }
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_reply_read_wirereader:4493 */
bool yarpdataplayer_IDL_step_helper::Reply::read(yarp::os::idl::WireReader& reader)
{
    if (!reader.readListReturn()) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
/* t_yarp_generator::generate_deserialize_field:1449 */
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    if (!reader.readBool(return_helper)) {
/* t_yarp_generator::generate_deserialize_field_fallback:1432 */
        reader.fail();
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_call:4531 */
void yarpdataplayer_IDL_step_helper::call(yarpdataplayer_IDL* ptr)
{
    reply.return_helper = ptr->step();
}

/* t_yarp_generator::generate_service_helper_classes_impl:4070 */
// setFrame helper class implementation
/* t_yarp_generator::generate_service_helper_classes_impl_ctor:4109 */
yarpdataplayer_IDL_setFrame_helper::yarpdataplayer_IDL_setFrame_helper(const std::int32_t frameNum) :
        cmd{frameNum}
{
}

/* t_yarp_generator::generate_service_helper_classes_impl_write:4136 */
bool yarpdataplayer_IDL_setFrame_helper::write(yarp::os::ConnectionWriter& connection) const
{
    return cmd.write(connection);
}

/* t_yarp_generator::generate_service_helper_classes_impl_read:4184 */
bool yarpdataplayer_IDL_setFrame_helper::read(yarp::os::ConnectionReader& connection)
{
    return reply.read(connection);
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_ctor:4156 */
yarpdataplayer_IDL_setFrame_helper::Command::Command(const std::int32_t frameNum) :
        frameNum{frameNum}
{
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_write_connectionwriter:4204 */
bool yarpdataplayer_IDL_setFrame_helper::Command::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    if (!writer.writeListHeader(s_cmd_len)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    return write(writer);
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_read_connectionreader:4226 */
bool yarpdataplayer_IDL_setFrame_helper::Command::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    if (!reader.readListHeader()) {
        reader.fail();
        return false;
    }
    return read(reader);
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_write_wirewriter:4256 */
bool yarpdataplayer_IDL_setFrame_helper::Command::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writeTag(writer)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    if (!writeArgs(writer)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_writetag:4278 */
bool yarpdataplayer_IDL_setFrame_helper::Command::writeTag(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeTag(s_tag, 1, s_tag_len)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_writeargs:4299 */
bool yarpdataplayer_IDL_setFrame_helper::Command::writeArgs(const yarp::os::idl::WireWriter& writer) const
{
/* t_yarp_generator::generate_serialize_field:1146 */
    if (!writer.writeI32(frameNum)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_read_wirereader:4327 */
bool yarpdataplayer_IDL_setFrame_helper::Command::read(yarp::os::idl::WireReader& reader)
{
    if (!readTag(reader)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    if (!readArgs(reader)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_readtag:4347 */
bool yarpdataplayer_IDL_setFrame_helper::Command::readTag(yarp::os::idl::WireReader& reader)
{
    std::string tag = reader.readTag(s_tag_len);
    if (reader.isError()) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    if (tag != s_tag) {
        reader.fail();
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_readargs:4375 */
bool yarpdataplayer_IDL_setFrame_helper::Command::readArgs(yarp::os::idl::WireReader& reader)
{
/* t_yarp_generator::generate_deserialize_field:1449 */
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    if (!reader.readI32(frameNum)) {
/* t_yarp_generator::generate_deserialize_field_fallback:1432 */
        reader.fail();
        return false;
    }
    if (!reader.noMore()) {
        reader.fail();
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_reply_write_connectionwriter:4405 */
bool yarpdataplayer_IDL_setFrame_helper::Reply::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    return write(writer);
}

/* t_yarp_generator::generate_service_helper_classes_impl_reply_read_connectionreader:4426 */
bool yarpdataplayer_IDL_setFrame_helper::Reply::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    return read(reader);
}

/* t_yarp_generator::generate_service_helper_classes_impl_reply_write_wirewriter:4447 */
bool yarpdataplayer_IDL_setFrame_helper::Reply::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.isNull()) {
        if (!writer.writeListHeader(s_reply_len)) {
            yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
            return false;
        }
/* t_yarp_generator::generate_serialize_field:1146 */
        if (!writer.writeBool(return_helper)) {
            yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
            return false;
        }
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_reply_read_wirereader:4493 */
bool yarpdataplayer_IDL_setFrame_helper::Reply::read(yarp::os::idl::WireReader& reader)
{
    if (!reader.readListReturn()) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
/* t_yarp_generator::generate_deserialize_field:1449 */
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    if (!reader.readBool(return_helper)) {
/* t_yarp_generator::generate_deserialize_field_fallback:1432 */
        reader.fail();
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_call:4531 */
void yarpdataplayer_IDL_setFrame_helper::call(yarpdataplayer_IDL* ptr)
{
    reply.return_helper = ptr->setFrame(cmd.frameNum);
}

/* t_yarp_generator::generate_service_helper_classes_impl:4070 */
// getFrame helper class implementation
/* t_yarp_generator::generate_service_helper_classes_impl_ctor:4109 */
yarpdataplayer_IDL_getFrame_helper::yarpdataplayer_IDL_getFrame_helper(const std::string& name) :
        cmd{name}
{
}

/* t_yarp_generator::generate_service_helper_classes_impl_write:4136 */
bool yarpdataplayer_IDL_getFrame_helper::write(yarp::os::ConnectionWriter& connection) const
{
    return cmd.write(connection);
}

/* t_yarp_generator::generate_service_helper_classes_impl_read:4184 */
bool yarpdataplayer_IDL_getFrame_helper::read(yarp::os::ConnectionReader& connection)
{
    return reply.read(connection);
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_ctor:4156 */
yarpdataplayer_IDL_getFrame_helper::Command::Command(const std::string& name) :
        name{name}
{
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_write_connectionwriter:4204 */
bool yarpdataplayer_IDL_getFrame_helper::Command::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    if (!writer.writeListHeader(s_cmd_len)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    return write(writer);
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_read_connectionreader:4226 */
bool yarpdataplayer_IDL_getFrame_helper::Command::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    if (!reader.readListHeader()) {
        reader.fail();
        return false;
    }
    return read(reader);
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_write_wirewriter:4256 */
bool yarpdataplayer_IDL_getFrame_helper::Command::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writeTag(writer)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    if (!writeArgs(writer)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_writetag:4278 */
bool yarpdataplayer_IDL_getFrame_helper::Command::writeTag(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeTag(s_tag, 1, s_tag_len)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_writeargs:4299 */
bool yarpdataplayer_IDL_getFrame_helper::Command::writeArgs(const yarp::os::idl::WireWriter& writer) const
{
/* t_yarp_generator::generate_serialize_field:1146 */
    if (!writer.writeString(name)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_read_wirereader:4327 */
bool yarpdataplayer_IDL_getFrame_helper::Command::read(yarp::os::idl::WireReader& reader)
{
    if (!readTag(reader)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    if (!readArgs(reader)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_readtag:4347 */
bool yarpdataplayer_IDL_getFrame_helper::Command::readTag(yarp::os::idl::WireReader& reader)
{
    std::string tag = reader.readTag(s_tag_len);
    if (reader.isError()) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    if (tag != s_tag) {
        reader.fail();
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_readargs:4375 */
bool yarpdataplayer_IDL_getFrame_helper::Command::readArgs(yarp::os::idl::WireReader& reader)
{
/* t_yarp_generator::generate_deserialize_field:1449 */
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    if (!reader.readString(name)) {
/* t_yarp_generator::generate_deserialize_field_fallback:1432 */
        reader.fail();
        return false;
    }
    if (!reader.noMore()) {
        reader.fail();
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_reply_write_connectionwriter:4405 */
bool yarpdataplayer_IDL_getFrame_helper::Reply::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    return write(writer);
}

/* t_yarp_generator::generate_service_helper_classes_impl_reply_read_connectionreader:4426 */
bool yarpdataplayer_IDL_getFrame_helper::Reply::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    return read(reader);
}

/* t_yarp_generator::generate_service_helper_classes_impl_reply_write_wirewriter:4447 */
bool yarpdataplayer_IDL_getFrame_helper::Reply::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.isNull()) {
        if (!writer.writeListHeader(s_reply_len)) {
            yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
            return false;
        }
/* t_yarp_generator::generate_serialize_field:1146 */
        if (!writer.writeI32(return_helper)) {
            yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
            return false;
        }
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_reply_read_wirereader:4493 */
bool yarpdataplayer_IDL_getFrame_helper::Reply::read(yarp::os::idl::WireReader& reader)
{
    if (!reader.readListReturn()) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
/* t_yarp_generator::generate_deserialize_field:1449 */
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    if (!reader.readI32(return_helper)) {
/* t_yarp_generator::generate_deserialize_field_fallback:1432 */
        reader.fail();
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_call:4531 */
void yarpdataplayer_IDL_getFrame_helper::call(yarpdataplayer_IDL* ptr)
{
    reply.return_helper = ptr->getFrame(cmd.name);
}

/* t_yarp_generator::generate_service_helper_classes_impl:4070 */
// load helper class implementation
/* t_yarp_generator::generate_service_helper_classes_impl_ctor:4109 */
yarpdataplayer_IDL_load_helper::yarpdataplayer_IDL_load_helper(const std::string& path) :
        cmd{path}
{
}

/* t_yarp_generator::generate_service_helper_classes_impl_write:4136 */
bool yarpdataplayer_IDL_load_helper::write(yarp::os::ConnectionWriter& connection) const
{
    return cmd.write(connection);
}

/* t_yarp_generator::generate_service_helper_classes_impl_read:4184 */
bool yarpdataplayer_IDL_load_helper::read(yarp::os::ConnectionReader& connection)
{
    return reply.read(connection);
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_ctor:4156 */
yarpdataplayer_IDL_load_helper::Command::Command(const std::string& path) :
        path{path}
{
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_write_connectionwriter:4204 */
bool yarpdataplayer_IDL_load_helper::Command::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    if (!writer.writeListHeader(s_cmd_len)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    return write(writer);
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_read_connectionreader:4226 */
bool yarpdataplayer_IDL_load_helper::Command::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    if (!reader.readListHeader()) {
        reader.fail();
        return false;
    }
    return read(reader);
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_write_wirewriter:4256 */
bool yarpdataplayer_IDL_load_helper::Command::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writeTag(writer)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    if (!writeArgs(writer)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_writetag:4278 */
bool yarpdataplayer_IDL_load_helper::Command::writeTag(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeTag(s_tag, 1, s_tag_len)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_writeargs:4299 */
bool yarpdataplayer_IDL_load_helper::Command::writeArgs(const yarp::os::idl::WireWriter& writer) const
{
/* t_yarp_generator::generate_serialize_field:1146 */
    if (!writer.writeString(path)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_read_wirereader:4327 */
bool yarpdataplayer_IDL_load_helper::Command::read(yarp::os::idl::WireReader& reader)
{
    if (!readTag(reader)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    if (!readArgs(reader)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_readtag:4347 */
bool yarpdataplayer_IDL_load_helper::Command::readTag(yarp::os::idl::WireReader& reader)
{
    std::string tag = reader.readTag(s_tag_len);
    if (reader.isError()) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    if (tag != s_tag) {
        reader.fail();
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_readargs:4375 */
bool yarpdataplayer_IDL_load_helper::Command::readArgs(yarp::os::idl::WireReader& reader)
{
/* t_yarp_generator::generate_deserialize_field:1449 */
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    if (!reader.readString(path)) {
/* t_yarp_generator::generate_deserialize_field_fallback:1432 */
        reader.fail();
        return false;
    }
    if (!reader.noMore()) {
        reader.fail();
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_reply_write_connectionwriter:4405 */
bool yarpdataplayer_IDL_load_helper::Reply::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    return write(writer);
}

/* t_yarp_generator::generate_service_helper_classes_impl_reply_read_connectionreader:4426 */
bool yarpdataplayer_IDL_load_helper::Reply::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    return read(reader);
}

/* t_yarp_generator::generate_service_helper_classes_impl_reply_write_wirewriter:4447 */
bool yarpdataplayer_IDL_load_helper::Reply::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.isNull()) {
        if (!writer.writeListHeader(s_reply_len)) {
            yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
            return false;
        }
/* t_yarp_generator::generate_serialize_field:1146 */
        if (!writer.writeBool(return_helper)) {
            yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
            return false;
        }
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_reply_read_wirereader:4493 */
bool yarpdataplayer_IDL_load_helper::Reply::read(yarp::os::idl::WireReader& reader)
{
    if (!reader.readListReturn()) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
/* t_yarp_generator::generate_deserialize_field:1449 */
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    if (!reader.readBool(return_helper)) {
/* t_yarp_generator::generate_deserialize_field_fallback:1432 */
        reader.fail();
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_call:4531 */
void yarpdataplayer_IDL_load_helper::call(yarpdataplayer_IDL* ptr)
{
    reply.return_helper = ptr->load(cmd.path);
}

/* t_yarp_generator::generate_service_helper_classes_impl:4070 */
// getSliderPercentage helper class implementation
/* t_yarp_generator::generate_service_helper_classes_impl_write:4136 */
bool yarpdataplayer_IDL_getSliderPercentage_helper::write(yarp::os::ConnectionWriter& connection) const
{
    return cmd.write(connection);
}

/* t_yarp_generator::generate_service_helper_classes_impl_read:4184 */
bool yarpdataplayer_IDL_getSliderPercentage_helper::read(yarp::os::ConnectionReader& connection)
{
    return reply.read(connection);
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_write_connectionwriter:4204 */
bool yarpdataplayer_IDL_getSliderPercentage_helper::Command::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    if (!writer.writeListHeader(s_cmd_len)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    return write(writer);
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_read_connectionreader:4226 */
bool yarpdataplayer_IDL_getSliderPercentage_helper::Command::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    if (!reader.readListHeader()) {
        reader.fail();
        return false;
    }
    return read(reader);
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_write_wirewriter:4256 */
bool yarpdataplayer_IDL_getSliderPercentage_helper::Command::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writeTag(writer)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    if (!writeArgs(writer)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_writetag:4278 */
bool yarpdataplayer_IDL_getSliderPercentage_helper::Command::writeTag(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeTag(s_tag, 1, s_tag_len)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_writeargs:4299 */
bool yarpdataplayer_IDL_getSliderPercentage_helper::Command::writeArgs(const yarp::os::idl::WireWriter& writer [[maybe_unused]]) const
{
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_read_wirereader:4327 */
bool yarpdataplayer_IDL_getSliderPercentage_helper::Command::read(yarp::os::idl::WireReader& reader)
{
    if (!readTag(reader)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    if (!readArgs(reader)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_readtag:4347 */
bool yarpdataplayer_IDL_getSliderPercentage_helper::Command::readTag(yarp::os::idl::WireReader& reader)
{
    std::string tag = reader.readTag(s_tag_len);
    if (reader.isError()) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    if (tag != s_tag) {
        reader.fail();
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_readargs:4375 */
bool yarpdataplayer_IDL_getSliderPercentage_helper::Command::readArgs(yarp::os::idl::WireReader& reader)
{
    if (!reader.noMore()) {
        reader.fail();
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_reply_write_connectionwriter:4405 */
bool yarpdataplayer_IDL_getSliderPercentage_helper::Reply::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    return write(writer);
}

/* t_yarp_generator::generate_service_helper_classes_impl_reply_read_connectionreader:4426 */
bool yarpdataplayer_IDL_getSliderPercentage_helper::Reply::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    return read(reader);
}

/* t_yarp_generator::generate_service_helper_classes_impl_reply_write_wirewriter:4447 */
bool yarpdataplayer_IDL_getSliderPercentage_helper::Reply::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.isNull()) {
        if (!writer.writeListHeader(s_reply_len)) {
            yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
            return false;
        }
/* t_yarp_generator::generate_serialize_field:1146 */
        if (!writer.writeI32(return_helper)) {
            yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
            return false;
        }
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_reply_read_wirereader:4493 */
bool yarpdataplayer_IDL_getSliderPercentage_helper::Reply::read(yarp::os::idl::WireReader& reader)
{
    if (!reader.readListReturn()) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
/* t_yarp_generator::generate_deserialize_field:1449 */
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    if (!reader.readI32(return_helper)) {
/* t_yarp_generator::generate_deserialize_field_fallback:1432 */
        reader.fail();
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_call:4531 */
void yarpdataplayer_IDL_getSliderPercentage_helper::call(yarpdataplayer_IDL* ptr)
{
    reply.return_helper = ptr->getSliderPercentage();
}

/* t_yarp_generator::generate_service_helper_classes_impl:4070 */
// getStatus helper class implementation
/* t_yarp_generator::generate_service_helper_classes_impl_write:4136 */
bool yarpdataplayer_IDL_getStatus_helper::write(yarp::os::ConnectionWriter& connection) const
{
    return cmd.write(connection);
}

/* t_yarp_generator::generate_service_helper_classes_impl_read:4184 */
bool yarpdataplayer_IDL_getStatus_helper::read(yarp::os::ConnectionReader& connection)
{
    return reply.read(connection);
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_write_connectionwriter:4204 */
bool yarpdataplayer_IDL_getStatus_helper::Command::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    if (!writer.writeListHeader(s_cmd_len)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    return write(writer);
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_read_connectionreader:4226 */
bool yarpdataplayer_IDL_getStatus_helper::Command::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    if (!reader.readListHeader()) {
        reader.fail();
        return false;
    }
    return read(reader);
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_write_wirewriter:4256 */
bool yarpdataplayer_IDL_getStatus_helper::Command::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writeTag(writer)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    if (!writeArgs(writer)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_writetag:4278 */
bool yarpdataplayer_IDL_getStatus_helper::Command::writeTag(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeTag(s_tag, 1, s_tag_len)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_writeargs:4299 */
bool yarpdataplayer_IDL_getStatus_helper::Command::writeArgs(const yarp::os::idl::WireWriter& writer [[maybe_unused]]) const
{
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_read_wirereader:4327 */
bool yarpdataplayer_IDL_getStatus_helper::Command::read(yarp::os::idl::WireReader& reader)
{
    if (!readTag(reader)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    if (!readArgs(reader)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_readtag:4347 */
bool yarpdataplayer_IDL_getStatus_helper::Command::readTag(yarp::os::idl::WireReader& reader)
{
    std::string tag = reader.readTag(s_tag_len);
    if (reader.isError()) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    if (tag != s_tag) {
        reader.fail();
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_readargs:4375 */
bool yarpdataplayer_IDL_getStatus_helper::Command::readArgs(yarp::os::idl::WireReader& reader)
{
    if (!reader.noMore()) {
        reader.fail();
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_reply_write_connectionwriter:4405 */
bool yarpdataplayer_IDL_getStatus_helper::Reply::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    return write(writer);
}

/* t_yarp_generator::generate_service_helper_classes_impl_reply_read_connectionreader:4426 */
bool yarpdataplayer_IDL_getStatus_helper::Reply::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    return read(reader);
}

/* t_yarp_generator::generate_service_helper_classes_impl_reply_write_wirewriter:4447 */
bool yarpdataplayer_IDL_getStatus_helper::Reply::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.isNull()) {
        if (!writer.writeListHeader(s_reply_len)) {
            yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
            return false;
        }
/* t_yarp_generator::generate_serialize_field:1146 */
        if (!writer.writeString(return_helper)) {
            yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
            return false;
        }
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_reply_read_wirereader:4493 */
bool yarpdataplayer_IDL_getStatus_helper::Reply::read(yarp::os::idl::WireReader& reader)
{
    if (!reader.readListReturn()) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
/* t_yarp_generator::generate_deserialize_field:1449 */
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    if (!reader.readString(return_helper)) {
/* t_yarp_generator::generate_deserialize_field_fallback:1432 */
        reader.fail();
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_call:4531 */
void yarpdataplayer_IDL_getStatus_helper::call(yarpdataplayer_IDL* ptr)
{
    reply.return_helper = ptr->getStatus();
}

/* t_yarp_generator::generate_service_helper_classes_impl:4070 */
// play helper class implementation
/* t_yarp_generator::generate_service_helper_classes_impl_write:4136 */
bool yarpdataplayer_IDL_play_helper::write(yarp::os::ConnectionWriter& connection) const
{
    return cmd.write(connection);
}

/* t_yarp_generator::generate_service_helper_classes_impl_read:4184 */
bool yarpdataplayer_IDL_play_helper::read(yarp::os::ConnectionReader& connection)
{
    return reply.read(connection);
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_write_connectionwriter:4204 */
bool yarpdataplayer_IDL_play_helper::Command::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    if (!writer.writeListHeader(s_cmd_len)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    return write(writer);
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_read_connectionreader:4226 */
bool yarpdataplayer_IDL_play_helper::Command::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    if (!reader.readListHeader()) {
        reader.fail();
        return false;
    }
    return read(reader);
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_write_wirewriter:4256 */
bool yarpdataplayer_IDL_play_helper::Command::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writeTag(writer)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    if (!writeArgs(writer)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_writetag:4278 */
bool yarpdataplayer_IDL_play_helper::Command::writeTag(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeTag(s_tag, 1, s_tag_len)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_writeargs:4299 */
bool yarpdataplayer_IDL_play_helper::Command::writeArgs(const yarp::os::idl::WireWriter& writer [[maybe_unused]]) const
{
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_read_wirereader:4327 */
bool yarpdataplayer_IDL_play_helper::Command::read(yarp::os::idl::WireReader& reader)
{
    if (!readTag(reader)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    if (!readArgs(reader)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_readtag:4347 */
bool yarpdataplayer_IDL_play_helper::Command::readTag(yarp::os::idl::WireReader& reader)
{
    std::string tag = reader.readTag(s_tag_len);
    if (reader.isError()) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    if (tag != s_tag) {
        reader.fail();
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_readargs:4375 */
bool yarpdataplayer_IDL_play_helper::Command::readArgs(yarp::os::idl::WireReader& reader)
{
    if (!reader.noMore()) {
        reader.fail();
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_reply_write_connectionwriter:4405 */
bool yarpdataplayer_IDL_play_helper::Reply::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    return write(writer);
}

/* t_yarp_generator::generate_service_helper_classes_impl_reply_read_connectionreader:4426 */
bool yarpdataplayer_IDL_play_helper::Reply::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    return read(reader);
}

/* t_yarp_generator::generate_service_helper_classes_impl_reply_write_wirewriter:4447 */
bool yarpdataplayer_IDL_play_helper::Reply::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.isNull()) {
        if (!writer.writeListHeader(s_reply_len)) {
            yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
            return false;
        }
/* t_yarp_generator::generate_serialize_field:1146 */
        if (!writer.writeBool(return_helper)) {
            yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
            return false;
        }
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_reply_read_wirereader:4493 */
bool yarpdataplayer_IDL_play_helper::Reply::read(yarp::os::idl::WireReader& reader)
{
    if (!reader.readListReturn()) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
/* t_yarp_generator::generate_deserialize_field:1449 */
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    if (!reader.readBool(return_helper)) {
/* t_yarp_generator::generate_deserialize_field_fallback:1432 */
        reader.fail();
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_call:4531 */
void yarpdataplayer_IDL_play_helper::call(yarpdataplayer_IDL* ptr)
{
    reply.return_helper = ptr->play();
}

/* t_yarp_generator::generate_service_helper_classes_impl:4070 */
// pause helper class implementation
/* t_yarp_generator::generate_service_helper_classes_impl_write:4136 */
bool yarpdataplayer_IDL_pause_helper::write(yarp::os::ConnectionWriter& connection) const
{
    return cmd.write(connection);
}

/* t_yarp_generator::generate_service_helper_classes_impl_read:4184 */
bool yarpdataplayer_IDL_pause_helper::read(yarp::os::ConnectionReader& connection)
{
    return reply.read(connection);
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_write_connectionwriter:4204 */
bool yarpdataplayer_IDL_pause_helper::Command::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    if (!writer.writeListHeader(s_cmd_len)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    return write(writer);
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_read_connectionreader:4226 */
bool yarpdataplayer_IDL_pause_helper::Command::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    if (!reader.readListHeader()) {
        reader.fail();
        return false;
    }
    return read(reader);
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_write_wirewriter:4256 */
bool yarpdataplayer_IDL_pause_helper::Command::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writeTag(writer)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    if (!writeArgs(writer)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_writetag:4278 */
bool yarpdataplayer_IDL_pause_helper::Command::writeTag(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeTag(s_tag, 1, s_tag_len)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_writeargs:4299 */
bool yarpdataplayer_IDL_pause_helper::Command::writeArgs(const yarp::os::idl::WireWriter& writer [[maybe_unused]]) const
{
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_read_wirereader:4327 */
bool yarpdataplayer_IDL_pause_helper::Command::read(yarp::os::idl::WireReader& reader)
{
    if (!readTag(reader)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    if (!readArgs(reader)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_readtag:4347 */
bool yarpdataplayer_IDL_pause_helper::Command::readTag(yarp::os::idl::WireReader& reader)
{
    std::string tag = reader.readTag(s_tag_len);
    if (reader.isError()) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    if (tag != s_tag) {
        reader.fail();
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_readargs:4375 */
bool yarpdataplayer_IDL_pause_helper::Command::readArgs(yarp::os::idl::WireReader& reader)
{
    if (!reader.noMore()) {
        reader.fail();
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_reply_write_connectionwriter:4405 */
bool yarpdataplayer_IDL_pause_helper::Reply::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    return write(writer);
}

/* t_yarp_generator::generate_service_helper_classes_impl_reply_read_connectionreader:4426 */
bool yarpdataplayer_IDL_pause_helper::Reply::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    return read(reader);
}

/* t_yarp_generator::generate_service_helper_classes_impl_reply_write_wirewriter:4447 */
bool yarpdataplayer_IDL_pause_helper::Reply::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.isNull()) {
        if (!writer.writeListHeader(s_reply_len)) {
            yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
            return false;
        }
/* t_yarp_generator::generate_serialize_field:1146 */
        if (!writer.writeBool(return_helper)) {
            yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
            return false;
        }
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_reply_read_wirereader:4493 */
bool yarpdataplayer_IDL_pause_helper::Reply::read(yarp::os::idl::WireReader& reader)
{
    if (!reader.readListReturn()) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
/* t_yarp_generator::generate_deserialize_field:1449 */
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    if (!reader.readBool(return_helper)) {
/* t_yarp_generator::generate_deserialize_field_fallback:1432 */
        reader.fail();
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_call:4531 */
void yarpdataplayer_IDL_pause_helper::call(yarpdataplayer_IDL* ptr)
{
    reply.return_helper = ptr->pause();
}

/* t_yarp_generator::generate_service_helper_classes_impl:4070 */
// stop helper class implementation
/* t_yarp_generator::generate_service_helper_classes_impl_write:4136 */
bool yarpdataplayer_IDL_stop_helper::write(yarp::os::ConnectionWriter& connection) const
{
    return cmd.write(connection);
}

/* t_yarp_generator::generate_service_helper_classes_impl_read:4184 */
bool yarpdataplayer_IDL_stop_helper::read(yarp::os::ConnectionReader& connection)
{
    return reply.read(connection);
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_write_connectionwriter:4204 */
bool yarpdataplayer_IDL_stop_helper::Command::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    if (!writer.writeListHeader(s_cmd_len)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    return write(writer);
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_read_connectionreader:4226 */
bool yarpdataplayer_IDL_stop_helper::Command::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    if (!reader.readListHeader()) {
        reader.fail();
        return false;
    }
    return read(reader);
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_write_wirewriter:4256 */
bool yarpdataplayer_IDL_stop_helper::Command::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writeTag(writer)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    if (!writeArgs(writer)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_writetag:4278 */
bool yarpdataplayer_IDL_stop_helper::Command::writeTag(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeTag(s_tag, 1, s_tag_len)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_writeargs:4299 */
bool yarpdataplayer_IDL_stop_helper::Command::writeArgs(const yarp::os::idl::WireWriter& writer [[maybe_unused]]) const
{
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_read_wirereader:4327 */
bool yarpdataplayer_IDL_stop_helper::Command::read(yarp::os::idl::WireReader& reader)
{
    if (!readTag(reader)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    if (!readArgs(reader)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_readtag:4347 */
bool yarpdataplayer_IDL_stop_helper::Command::readTag(yarp::os::idl::WireReader& reader)
{
    std::string tag = reader.readTag(s_tag_len);
    if (reader.isError()) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    if (tag != s_tag) {
        reader.fail();
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_readargs:4375 */
bool yarpdataplayer_IDL_stop_helper::Command::readArgs(yarp::os::idl::WireReader& reader)
{
    if (!reader.noMore()) {
        reader.fail();
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_reply_write_connectionwriter:4405 */
bool yarpdataplayer_IDL_stop_helper::Reply::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    return write(writer);
}

/* t_yarp_generator::generate_service_helper_classes_impl_reply_read_connectionreader:4426 */
bool yarpdataplayer_IDL_stop_helper::Reply::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    return read(reader);
}

/* t_yarp_generator::generate_service_helper_classes_impl_reply_write_wirewriter:4447 */
bool yarpdataplayer_IDL_stop_helper::Reply::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.isNull()) {
        if (!writer.writeListHeader(s_reply_len)) {
            yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
            return false;
        }
/* t_yarp_generator::generate_serialize_field:1146 */
        if (!writer.writeBool(return_helper)) {
            yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
            return false;
        }
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_reply_read_wirereader:4493 */
bool yarpdataplayer_IDL_stop_helper::Reply::read(yarp::os::idl::WireReader& reader)
{
    if (!reader.readListReturn()) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
/* t_yarp_generator::generate_deserialize_field:1449 */
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    if (!reader.readBool(return_helper)) {
/* t_yarp_generator::generate_deserialize_field_fallback:1432 */
        reader.fail();
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_call:4531 */
void yarpdataplayer_IDL_stop_helper::call(yarpdataplayer_IDL* ptr)
{
    reply.return_helper = ptr->stop();
}

/* t_yarp_generator::generate_service_helper_classes_impl:4070 */
// quit helper class implementation
/* t_yarp_generator::generate_service_helper_classes_impl_write:4136 */
bool yarpdataplayer_IDL_quit_helper::write(yarp::os::ConnectionWriter& connection) const
{
    return cmd.write(connection);
}

/* t_yarp_generator::generate_service_helper_classes_impl_read:4184 */
bool yarpdataplayer_IDL_quit_helper::read(yarp::os::ConnectionReader& connection)
{
    return reply.read(connection);
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_write_connectionwriter:4204 */
bool yarpdataplayer_IDL_quit_helper::Command::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    if (!writer.writeListHeader(s_cmd_len)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    return write(writer);
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_read_connectionreader:4226 */
bool yarpdataplayer_IDL_quit_helper::Command::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    if (!reader.readListHeader()) {
        reader.fail();
        return false;
    }
    return read(reader);
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_write_wirewriter:4256 */
bool yarpdataplayer_IDL_quit_helper::Command::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writeTag(writer)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    if (!writeArgs(writer)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_writetag:4278 */
bool yarpdataplayer_IDL_quit_helper::Command::writeTag(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeTag(s_tag, 1, s_tag_len)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_writeargs:4299 */
bool yarpdataplayer_IDL_quit_helper::Command::writeArgs(const yarp::os::idl::WireWriter& writer [[maybe_unused]]) const
{
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_read_wirereader:4327 */
bool yarpdataplayer_IDL_quit_helper::Command::read(yarp::os::idl::WireReader& reader)
{
    if (!readTag(reader)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    if (!readArgs(reader)) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_readtag:4347 */
bool yarpdataplayer_IDL_quit_helper::Command::readTag(yarp::os::idl::WireReader& reader)
{
    std::string tag = reader.readTag(s_tag_len);
    if (reader.isError()) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
    if (tag != s_tag) {
        reader.fail();
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_command_readargs:4375 */
bool yarpdataplayer_IDL_quit_helper::Command::readArgs(yarp::os::idl::WireReader& reader)
{
    if (!reader.noMore()) {
        reader.fail();
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_reply_write_connectionwriter:4405 */
bool yarpdataplayer_IDL_quit_helper::Reply::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    return write(writer);
}

/* t_yarp_generator::generate_service_helper_classes_impl_reply_read_connectionreader:4426 */
bool yarpdataplayer_IDL_quit_helper::Reply::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    return read(reader);
}

/* t_yarp_generator::generate_service_helper_classes_impl_reply_write_wirewriter:4447 */
bool yarpdataplayer_IDL_quit_helper::Reply::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.isNull()) {
        if (!writer.writeListHeader(s_reply_len)) {
            yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
            return false;
        }
/* t_yarp_generator::generate_serialize_field:1146 */
        if (!writer.writeBool(return_helper)) {
            yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
            return false;
        }
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_reply_read_wirereader:4493 */
bool yarpdataplayer_IDL_quit_helper::Reply::read(yarp::os::idl::WireReader& reader)
{
    if (!reader.readListReturn()) {
        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
        return false;
    }
/* t_yarp_generator::generate_deserialize_field:1449 */
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    if (!reader.readBool(return_helper)) {
/* t_yarp_generator::generate_deserialize_field_fallback:1432 */
        reader.fail();
        return false;
    }
    return true;
}

/* t_yarp_generator::generate_service_helper_classes_impl_call:4531 */
void yarpdataplayer_IDL_quit_helper::call(yarpdataplayer_IDL* ptr)
{
    reply.return_helper = ptr->quit();
}

/* t_yarp_generator::generate_service_constructor:4571 */
// Constructor
yarpdataplayer_IDL::yarpdataplayer_IDL()
{
    yarp().setOwner(*this);
}

/* t_yarp_generator::generate_service_method:4596 */
bool yarpdataplayer_IDL::step()
{
    if (!yarp().canWrite()) {
        yError("Missing server method '%s'?", yarpdataplayer_IDL_step_helper::s_prototype);
    }
    yarpdataplayer_IDL_step_helper helper{};
    bool ok = yarp().write(helper, helper);
    return ok ? helper.reply.return_helper : bool{};
}

/* t_yarp_generator::generate_service_method:4596 */
bool yarpdataplayer_IDL::setFrame(const std::int32_t frameNum)
{
    if (!yarp().canWrite()) {
        yError("Missing server method '%s'?", yarpdataplayer_IDL_setFrame_helper::s_prototype);
    }
    yarpdataplayer_IDL_setFrame_helper helper{frameNum};
    bool ok = yarp().write(helper, helper);
    return ok ? helper.reply.return_helper : bool{};
}

/* t_yarp_generator::generate_service_method:4596 */
std::int32_t yarpdataplayer_IDL::getFrame(const std::string& name)
{
    if (!yarp().canWrite()) {
        yError("Missing server method '%s'?", yarpdataplayer_IDL_getFrame_helper::s_prototype);
    }
    yarpdataplayer_IDL_getFrame_helper helper{name};
    bool ok = yarp().write(helper, helper);
    return ok ? helper.reply.return_helper : std::int32_t{};
}

/* t_yarp_generator::generate_service_method:4596 */
bool yarpdataplayer_IDL::load(const std::string& path)
{
    if (!yarp().canWrite()) {
        yError("Missing server method '%s'?", yarpdataplayer_IDL_load_helper::s_prototype);
    }
    yarpdataplayer_IDL_load_helper helper{path};
    bool ok = yarp().write(helper, helper);
    return ok ? helper.reply.return_helper : bool{};
}

/* t_yarp_generator::generate_service_method:4596 */
std::int32_t yarpdataplayer_IDL::getSliderPercentage()
{
    if (!yarp().canWrite()) {
        yError("Missing server method '%s'?", yarpdataplayer_IDL_getSliderPercentage_helper::s_prototype);
    }
    yarpdataplayer_IDL_getSliderPercentage_helper helper{};
    bool ok = yarp().write(helper, helper);
    return ok ? helper.reply.return_helper : std::int32_t{};
}

/* t_yarp_generator::generate_service_method:4596 */
std::string yarpdataplayer_IDL::getStatus()
{
    if (!yarp().canWrite()) {
        yError("Missing server method '%s'?", yarpdataplayer_IDL_getStatus_helper::s_prototype);
    }
    yarpdataplayer_IDL_getStatus_helper helper{};
    bool ok = yarp().write(helper, helper);
    return ok ? helper.reply.return_helper : std::string{};
}

/* t_yarp_generator::generate_service_method:4596 */
bool yarpdataplayer_IDL::play()
{
    if (!yarp().canWrite()) {
        yError("Missing server method '%s'?", yarpdataplayer_IDL_play_helper::s_prototype);
    }
    yarpdataplayer_IDL_play_helper helper{};
    bool ok = yarp().write(helper, helper);
    return ok ? helper.reply.return_helper : bool{};
}

/* t_yarp_generator::generate_service_method:4596 */
bool yarpdataplayer_IDL::pause()
{
    if (!yarp().canWrite()) {
        yError("Missing server method '%s'?", yarpdataplayer_IDL_pause_helper::s_prototype);
    }
    yarpdataplayer_IDL_pause_helper helper{};
    bool ok = yarp().write(helper, helper);
    return ok ? helper.reply.return_helper : bool{};
}

/* t_yarp_generator::generate_service_method:4596 */
bool yarpdataplayer_IDL::stop()
{
    if (!yarp().canWrite()) {
        yError("Missing server method '%s'?", yarpdataplayer_IDL_stop_helper::s_prototype);
    }
    yarpdataplayer_IDL_stop_helper helper{};
    bool ok = yarp().write(helper, helper);
    return ok ? helper.reply.return_helper : bool{};
}

/* t_yarp_generator::generate_service_method:4596 */
bool yarpdataplayer_IDL::quit()
{
    if (!yarp().canWrite()) {
        yError("Missing server method '%s'?", yarpdataplayer_IDL_quit_helper::s_prototype);
    }
    yarpdataplayer_IDL_quit_helper helper{};
    bool ok = yarp().write(helper, helper);
    return ok ? helper.reply.return_helper : bool{};
}

/* t_yarp_generator::generate_service_help:4649 */
// help method
std::vector<std::string> yarpdataplayer_IDL::help(const std::string& functionName)
{
    bool showAll = (functionName == "--all");
    std::vector<std::string> helpString;
    if (showAll) {
        helpString.emplace_back("*** Available commands:");
        helpString.emplace_back(yarpdataplayer_IDL_step_helper::s_tag);
        helpString.emplace_back(yarpdataplayer_IDL_setFrame_helper::s_tag);
        helpString.emplace_back(yarpdataplayer_IDL_getFrame_helper::s_tag);
        helpString.emplace_back(yarpdataplayer_IDL_load_helper::s_tag);
        helpString.emplace_back(yarpdataplayer_IDL_getSliderPercentage_helper::s_tag);
        helpString.emplace_back(yarpdataplayer_IDL_getStatus_helper::s_tag);
        helpString.emplace_back(yarpdataplayer_IDL_play_helper::s_tag);
        helpString.emplace_back(yarpdataplayer_IDL_pause_helper::s_tag);
        helpString.emplace_back(yarpdataplayer_IDL_stop_helper::s_tag);
        helpString.emplace_back(yarpdataplayer_IDL_quit_helper::s_tag);
        helpString.emplace_back("help");
    } else {
        if (functionName == yarpdataplayer_IDL_step_helper::s_tag) {
            helpString.emplace_back(yarpdataplayer_IDL_step_helper::s_prototype);
            helpString.emplace_back(yarpdataplayer_IDL_step_helper::s_help);
        }
        if (functionName == yarpdataplayer_IDL_setFrame_helper::s_tag) {
            helpString.emplace_back(yarpdataplayer_IDL_setFrame_helper::s_prototype);
            helpString.emplace_back(yarpdataplayer_IDL_setFrame_helper::s_help);
        }
        if (functionName == yarpdataplayer_IDL_getFrame_helper::s_tag) {
            helpString.emplace_back(yarpdataplayer_IDL_getFrame_helper::s_prototype);
            helpString.emplace_back(yarpdataplayer_IDL_getFrame_helper::s_help);
        }
        if (functionName == yarpdataplayer_IDL_load_helper::s_tag) {
            helpString.emplace_back(yarpdataplayer_IDL_load_helper::s_prototype);
            helpString.emplace_back(yarpdataplayer_IDL_load_helper::s_help);
        }
        if (functionName == yarpdataplayer_IDL_getSliderPercentage_helper::s_tag) {
            helpString.emplace_back(yarpdataplayer_IDL_getSliderPercentage_helper::s_prototype);
            helpString.emplace_back(yarpdataplayer_IDL_getSliderPercentage_helper::s_help);
        }
        if (functionName == yarpdataplayer_IDL_getStatus_helper::s_tag) {
            helpString.emplace_back(yarpdataplayer_IDL_getStatus_helper::s_prototype);
            helpString.emplace_back(yarpdataplayer_IDL_getStatus_helper::s_help);
        }
        if (functionName == yarpdataplayer_IDL_play_helper::s_tag) {
            helpString.emplace_back(yarpdataplayer_IDL_play_helper::s_prototype);
            helpString.emplace_back(yarpdataplayer_IDL_play_helper::s_help);
        }
        if (functionName == yarpdataplayer_IDL_pause_helper::s_tag) {
            helpString.emplace_back(yarpdataplayer_IDL_pause_helper::s_prototype);
            helpString.emplace_back(yarpdataplayer_IDL_pause_helper::s_help);
        }
        if (functionName == yarpdataplayer_IDL_stop_helper::s_tag) {
            helpString.emplace_back(yarpdataplayer_IDL_stop_helper::s_prototype);
            helpString.emplace_back(yarpdataplayer_IDL_stop_helper::s_help);
        }
        if (functionName == yarpdataplayer_IDL_quit_helper::s_tag) {
            helpString.emplace_back(yarpdataplayer_IDL_quit_helper::s_prototype);
            helpString.emplace_back(yarpdataplayer_IDL_quit_helper::s_help);
        }
        if (functionName == "help") {
            helpString.emplace_back("std::vector<std::string> help(const std::string& functionName = \"--all\")");
            helpString.emplace_back("Return list of available commands, or help message for a specific function");
            helpString.emplace_back("@param functionName name of command for which to get a detailed description. If none or '--all' is provided, print list of available commands");
            helpString.emplace_back("@return list of strings (one string per line)");
        }
    }
    if (helpString.empty()) {
        helpString.emplace_back("Command not found");
    }
    return helpString;
}

/* t_yarp_generator::generate_service_read:4731 */
// read from ConnectionReader
bool yarpdataplayer_IDL::read(yarp::os::ConnectionReader& connection)
{
    constexpr size_t max_tag_len = 1;
    size_t tag_len = 1;

    yarp::os::idl::WireReader reader(connection);
    reader.expectAccept();
    if (!reader.readListHeader()) {
        reader.fail();
        return false;
    }

    std::string tag = reader.readTag(1);
    bool direct = (tag == "__direct__");
    if (direct) {
        tag = reader.readTag(1);
    }
    while (tag_len <= max_tag_len && !reader.isError()) {
        if (tag == yarpdataplayer_IDL_step_helper::s_tag) {
            yarpdataplayer_IDL_step_helper helper;
            if (!helper.cmd.readArgs(reader)) {
                yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
                return false;
            }

            helper.call(this);

            yarp::os::idl::WireWriter writer(reader);
            if (!helper.reply.write(writer)) {
                yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
                return false;
            }
            reader.accept();
            return true;
        }
        if (tag == yarpdataplayer_IDL_setFrame_helper::s_tag) {
            yarpdataplayer_IDL_setFrame_helper helper;
            if (!helper.cmd.readArgs(reader)) {
                yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
                return false;
            }

            helper.call(this);

            yarp::os::idl::WireWriter writer(reader);
            if (!helper.reply.write(writer)) {
                yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
                return false;
            }
            reader.accept();
            return true;
        }
        if (tag == yarpdataplayer_IDL_getFrame_helper::s_tag) {
            yarpdataplayer_IDL_getFrame_helper helper;
            if (!helper.cmd.readArgs(reader)) {
                yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
                return false;
            }

            helper.call(this);

            yarp::os::idl::WireWriter writer(reader);
            if (!helper.reply.write(writer)) {
                yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
                return false;
            }
            reader.accept();
            return true;
        }
        if (tag == yarpdataplayer_IDL_load_helper::s_tag) {
            yarpdataplayer_IDL_load_helper helper;
            if (!helper.cmd.readArgs(reader)) {
                yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
                return false;
            }

            helper.call(this);

            yarp::os::idl::WireWriter writer(reader);
            if (!helper.reply.write(writer)) {
                yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
                return false;
            }
            reader.accept();
            return true;
        }
        if (tag == yarpdataplayer_IDL_getSliderPercentage_helper::s_tag) {
            yarpdataplayer_IDL_getSliderPercentage_helper helper;
            if (!helper.cmd.readArgs(reader)) {
                yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
                return false;
            }

            helper.call(this);

            yarp::os::idl::WireWriter writer(reader);
            if (!helper.reply.write(writer)) {
                yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
                return false;
            }
            reader.accept();
            return true;
        }
        if (tag == yarpdataplayer_IDL_getStatus_helper::s_tag) {
            yarpdataplayer_IDL_getStatus_helper helper;
            if (!helper.cmd.readArgs(reader)) {
                yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
                return false;
            }

            helper.call(this);

            yarp::os::idl::WireWriter writer(reader);
            if (!helper.reply.write(writer)) {
                yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
                return false;
            }
            reader.accept();
            return true;
        }
        if (tag == yarpdataplayer_IDL_play_helper::s_tag) {
            yarpdataplayer_IDL_play_helper helper;
            if (!helper.cmd.readArgs(reader)) {
                yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
                return false;
            }

            helper.call(this);

            yarp::os::idl::WireWriter writer(reader);
            if (!helper.reply.write(writer)) {
                yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
                return false;
            }
            reader.accept();
            return true;
        }
        if (tag == yarpdataplayer_IDL_pause_helper::s_tag) {
            yarpdataplayer_IDL_pause_helper helper;
            if (!helper.cmd.readArgs(reader)) {
                yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
                return false;
            }

            helper.call(this);

            yarp::os::idl::WireWriter writer(reader);
            if (!helper.reply.write(writer)) {
                yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
                return false;
            }
            reader.accept();
            return true;
        }
        if (tag == yarpdataplayer_IDL_stop_helper::s_tag) {
            yarpdataplayer_IDL_stop_helper helper;
            if (!helper.cmd.readArgs(reader)) {
                yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
                return false;
            }

            helper.call(this);

            yarp::os::idl::WireWriter writer(reader);
            if (!helper.reply.write(writer)) {
                yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
                return false;
            }
            reader.accept();
            return true;
        }
        if (tag == yarpdataplayer_IDL_quit_helper::s_tag) {
            yarpdataplayer_IDL_quit_helper helper;
            if (!helper.cmd.readArgs(reader)) {
                yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
                return false;
            }

            helper.call(this);

            yarp::os::idl::WireWriter writer(reader);
            if (!helper.reply.write(writer)) {
                yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
                return false;
            }
            reader.accept();
            return true;
        }
        if (tag == "help") {
            std::string functionName;
            if (!reader.readString(functionName)) {
                functionName = "--all";
            }
            auto help_strings = help(functionName);
            yarp::os::idl::WireWriter writer(reader);
            if (!writer.isNull()) {
                if (!writer.writeListHeader(2)) {
                    yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
                    return false;
                }
                if (!writer.writeTag("many", 1, 0)) {
                    yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
                    return false;
                }
                if (!writer.writeListBegin(0, help_strings.size())) {
                    yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
                    return false;
                }
                for (const auto& help_string : help_strings) {
                    if (!writer.writeString(help_string)) {
                        yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
                        return false;
                    }
                }
                if (!writer.writeListEnd()) {
                    yWarning("%s:%d - %s", __FILE__, __LINE__, __YFUNCTION__);
                    return false;
                }
            }
            reader.accept();
            return true;
        }
        if (reader.noMore()) {
            reader.fail();
            return false;
        }
        std::string next_tag = reader.readTag(1);
        if (next_tag.empty()) {
            break;
        }
        tag.append("_").append(next_tag);
        tag_len = std::count(tag.begin(), tag.end(), '_') + 1;
    }
    return false;
}
