/*
 * SPDX-FileCopyrightText: 2006-2021 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: BSD-3-Clause
 */

// Autogenerated by Thrift Compiler (0.14.1-yarped)
//
// This is an automatically generated file.
// It could get re-generated if the ALLOW_IDL_GENERATION flag is on.

#ifndef YARP_THRIFT_GENERATOR_STRUCT_MAP2DPATHDATASERIALIZER_H
#define YARP_THRIFT_GENERATOR_STRUCT_MAP2DPATHDATASERIALIZER_H

#include <yarp/dev/api.h>

#include <yarp/os/WireSerializer.h>
#include <yarp/dev/Nav2D/Map2DPathDataStorage.h>
#include <yarp/dev/Map2DLocation.h> //needed in .h
#include <yarp/dev/Nav2D/Map2DLocationDataSerializer.h> //needed in .h

namespace yarp::dev::Nav2D {

class YARP_dev_API Map2DPathDataSerializer :
        public yarp::os::WireSerializer<Map2DPathDataStorage>{
public:
using WireSerializer::WireSerializer;

    // Read structure on a Wire
    bool read(yarp::os::idl::WireReader& reader) override;

    // Read structure on a Connection
    bool read(yarp::os::ConnectionReader& connection) override;

    // Write structure on a Wire
    bool write(const yarp::os::idl::WireWriter& writer) const override;

    // Write structure on a Connection
    bool write(yarp::os::ConnectionWriter& connection) const override;

    // Convert to a printable string
    std::string toString() const;

    // If you want to serialize this class without nesting, use this helper
    typedef yarp::os::idl::Unwrapped<Map2DPathDataSerializer> unwrapped;

private:
    // read/write waypoints field
    bool read_waypoints(yarp::os::idl::WireReader& reader);
    bool write_waypoints(const yarp::os::idl::WireWriter& writer) const;
    bool nested_read_waypoints(yarp::os::idl::WireReader& reader);
    bool nested_write_waypoints(const yarp::os::idl::WireWriter& writer) const;

    // read/write description field
    bool read_description(yarp::os::idl::WireReader& reader);
    bool write_description(const yarp::os::idl::WireWriter& writer) const;
    bool nested_read_description(yarp::os::idl::WireReader& reader);
    bool nested_write_description(const yarp::os::idl::WireWriter& writer) const;
};

} // namespace yarp::dev::Nav2D

#endif // YARP_THRIFT_GENERATOR_STRUCT_MAP2DPATHDATASERIALIZER_H
