/*
 * SPDX-FileCopyrightText: 2006-2021 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: BSD-3-Clause
 */

// Autogenerated by Thrift Compiler (0.14.1-yarped)
//
// This is an automatically generated file.
// It could get re-generated if the ALLOW_IDL_GENERATION flag is on.

#ifndef YARP_THRIFT_GENERATOR_STRUCT_MOBILEBASEVELOCITYSERIALIZER_H
#define YARP_THRIFT_GENERATOR_STRUCT_MOBILEBASEVELOCITYSERIALIZER_H

#include <yarp/dev/api.h>

#include <yarp/os/WireSerializer.h>
#include <yarp/dev/Nav2D/MobileBaseVelocityStorage.h>

namespace yarp::dev::Nav2D {

class YARP_dev_API MobileBaseVelocitySerializer :
        public yarp::os::WireSerializer<MobileBaseVelocityStorage>{
public:
using WireSerializer::WireSerializer;

    // Read structure on a Wire
    bool read(yarp::os::idl::WireReader& reader) override;

    // Read structure on a Connection
    bool read(yarp::os::ConnectionReader& connection) override;

    // Write structure on a Wire
    bool write(const yarp::os::idl::WireWriter& writer) const override;

    // Write structure on a Connection
    bool write(yarp::os::ConnectionWriter& connection) const override;

    // Convert to a printable string
    std::string toString() const;

    // If you want to serialize this class without nesting, use this helper
    typedef yarp::os::idl::Unwrapped<MobileBaseVelocitySerializer> unwrapped;

private:
    // read/write vel_x field
    bool read_vel_x(yarp::os::idl::WireReader& reader);
    bool write_vel_x(const yarp::os::idl::WireWriter& writer) const;
    bool nested_read_vel_x(yarp::os::idl::WireReader& reader);
    bool nested_write_vel_x(const yarp::os::idl::WireWriter& writer) const;

    // read/write vel_y field
    bool read_vel_y(yarp::os::idl::WireReader& reader);
    bool write_vel_y(const yarp::os::idl::WireWriter& writer) const;
    bool nested_read_vel_y(yarp::os::idl::WireReader& reader);
    bool nested_write_vel_y(const yarp::os::idl::WireWriter& writer) const;

    // read/write vel_theta field
    bool read_vel_theta(yarp::os::idl::WireReader& reader);
    bool write_vel_theta(const yarp::os::idl::WireWriter& writer) const;
    bool nested_read_vel_theta(yarp::os::idl::WireReader& reader);
    bool nested_write_vel_theta(const yarp::os::idl::WireWriter& writer) const;
};

} // namespace yarp::dev::Nav2D

#endif // YARP_THRIFT_GENERATOR_STRUCT_MOBILEBASEVELOCITYSERIALIZER_H
