/*
 * SPDX-FileCopyrightText: 2006-2021 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: BSD-3-Clause
 */

// Autogenerated by Thrift Compiler (0.14.1-yarped)
//
// This is an automatically generated file.
// It could get re-generated if the ALLOW_IDL_GENERATION flag is on.

#ifndef YARP_THRIFT_GENERATOR_STRUCT_MOBILEBASEVELOCITYSTORAGE_H
#define YARP_THRIFT_GENERATOR_STRUCT_MOBILEBASEVELOCITYSTORAGE_H

#include <yarp/dev/api.h>

#include <cstdint>
#include <cstdio>
#include <map>
#include <set>
#include <string>
#include <vector>

namespace yarp::dev::Nav2D {

class YARP_dev_API MobileBaseVelocityStorage
{
public:
    // Fields
    /**
     * velocity of the robot [m/s]
     */
    double vel_x{0.0};
    /**
     * velocity of the robot [m/s]
     */
    double vel_y{0.0};
    /**
     * angular velocity of the robot [deg/s]
     */
    double vel_theta{0.0};

    // Default constructor
    MobileBaseVelocityStorage() = default;

    // Constructor with field values
    MobileBaseVelocityStorage(const double vel_x,
                              const double vel_y,
                              const double vel_theta);

};

} // namespace yarp::dev::Nav2D

#endif // YARP_THRIFT_GENERATOR_STRUCT_MOBILEBASEVELOCITYSTORAGE_H
