/*
 * SPDX-FileCopyrightText: 2006-2021 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: BSD-3-Clause
 */

// Autogenerated by Thrift Compiler (0.14.1-yarped)
//
// This is an automatically generated file.
// It could get re-generated if the ALLOW_IDL_GENERATION flag is on.

#include <yarp/dev/Nav2D/MobileBaseVelocityStorage.h>

namespace yarp::dev::Nav2D {

// Constructor with field values
MobileBaseVelocityStorage::MobileBaseVelocityStorage(const double vel_x,
                                                     const double vel_y,
                                                     const double vel_theta) :
        vel_x(vel_x),
        vel_y(vel_y),
        vel_theta(vel_theta)
{
}


} // namespace yarp::dev::Nav2D
