/*
 * SPDX-FileCopyrightText: 2006-2021 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: BSD-3-Clause
 */

// Autogenerated by Thrift Compiler (0.14.1-yarped)
//
// This is an automatically generated file.
// It could get re-generated if the ALLOW_IDL_GENERATION flag is on.

#include <yarp/dev/Nav2D/OdometryDataStorage.h>

namespace yarp::dev::Nav2D {

// Constructor with field values
OdometryDataStorage::OdometryDataStorage(const double odom_x,
                                         const double odom_y,
                                         const double odom_theta,
                                         const double base_vel_x,
                                         const double base_vel_y,
                                         const double base_vel_theta,
                                         const double odom_vel_x,
                                         const double odom_vel_y,
                                         const double odom_vel_theta) :
        odom_x(odom_x),
        odom_y(odom_y),
        odom_theta(odom_theta),
        base_vel_x(base_vel_x),
        base_vel_y(base_vel_y),
        base_vel_theta(base_vel_theta),
        odom_vel_x(odom_vel_x),
        odom_vel_y(odom_vel_y),
        odom_vel_theta(odom_vel_theta)
{
}


} // namespace yarp::dev::Nav2D
