/* t_yarp_generator::generate_service:3616 */
/*
 * SPDX-FileCopyrightText: 2006-2021 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: BSD-3-Clause
 */

// Autogenerated by Thrift Compiler (0.14.1-yarped)
//
// This is an automatically generated file.
// It could get re-generated if the ALLOW_IDL_GENERATION flag is on.

#ifndef YARP_THRIFT_GENERATOR_SERVICE_YARPROBOTINTERFACERPC_H
#define YARP_THRIFT_GENERATOR_SERVICE_YARPROBOTINTERFACERPC_H

#include <yarp/os/Wire.h>
#include <yarp/os/idl/WireTypes.h>

/* t_yarp_generator::generate_service:3712 */
class yarprobotinterfaceRpc :
        public yarp::os::Wire
{
public:
/* t_yarp_generator::generate_service_constructor:4424 */
    // Constructor
    yarprobotinterfaceRpc();

/* t_yarp_generator::generate_service_method:4449 */
    /**
     * Returns current phase.
     */
    virtual std::string get_phase();

/* t_yarp_generator::generate_service_method:4449 */
    /**
     * Returns current level.
     */
    virtual std::int32_t get_level();

/* t_yarp_generator::generate_service_method:4449 */
    /**
     * Returns robot name.
     */
    virtual std::string get_robot();

/* t_yarp_generator::generate_service_method:4449 */
    /**
     * Returns true if yarprobotinterface is ready (all startup actions
     * performed and no interrupt called).
     */
    virtual bool is_ready();

/* t_yarp_generator::generate_service_method:4449 */
    /**
     * Closes yarprobotinterface.
     */
    virtual std::string quit();

/* t_yarp_generator::generate_service_method:4449 */
    /**
     * Closes yarprobotinterface.
     */
    virtual std::string bye();

/* t_yarp_generator::generate_service_method:4449 */
    /**
     * Closes yarprobotinterface.
     */
    virtual std::string exit();

/* t_yarp_generator::generate_service_help:4502 */
    // help method
    virtual std::vector<std::string> help(const std::string& functionName = "--all");

/* t_yarp_generator::generate_service_read:4584 */
    // read from ConnectionReader
    bool read(yarp::os::ConnectionReader& connection) override;
};

#endif // YARP_THRIFT_GENERATOR_SERVICE_YARPROBOTINTERFACERPC_H
