/*
 * SPDX-FileCopyrightText: 2006-2021 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: BSD-3-Clause
 */

// Autogenerated by Thrift Compiler (0.14.1-yarped)
//
// This is an automatically generated file.
// It could get re-generated if the ALLOW_IDL_GENERATION flag is on.

#include <yarp/dev/impl/jointDataStorage.h>

namespace yarp::dev::impl {

// Constructor with field values
jointDataStorage::jointDataStorage(const std::vector<double>& jointPosition,
                                   const bool jointPosition_isValid,
                                   const std::vector<double>& jointVelocity,
                                   const bool jointVelocity_isValid,
                                   const std::vector<double>& jointAcceleration,
                                   const bool jointAcceleration_isValid,
                                   const std::vector<double>& motorPosition,
                                   const bool motorPosition_isValid,
                                   const std::vector<double>& motorVelocity,
                                   const bool motorVelocity_isValid,
                                   const std::vector<double>& motorAcceleration,
                                   const bool motorAcceleration_isValid,
                                   const std::vector<double>& torque,
                                   const bool torque_isValid,
                                   const std::vector<double>& pwmDutycycle,
                                   const bool pwmDutycycle_isValid,
                                   const std::vector<double>& current,
                                   const bool current_isValid,
                                   const std::vector<std::int32_t>& controlMode,
                                   const bool controlMode_isValid,
                                   const std::vector<std::int32_t>& interactionMode,
                                   const bool interactionMode_isValid) :
        jointPosition(jointPosition),
        jointPosition_isValid(jointPosition_isValid),
        jointVelocity(jointVelocity),
        jointVelocity_isValid(jointVelocity_isValid),
        jointAcceleration(jointAcceleration),
        jointAcceleration_isValid(jointAcceleration_isValid),
        motorPosition(motorPosition),
        motorPosition_isValid(motorPosition_isValid),
        motorVelocity(motorVelocity),
        motorVelocity_isValid(motorVelocity_isValid),
        motorAcceleration(motorAcceleration),
        motorAcceleration_isValid(motorAcceleration_isValid),
        torque(torque),
        torque_isValid(torque_isValid),
        pwmDutycycle(pwmDutycycle),
        pwmDutycycle_isValid(pwmDutycycle_isValid),
        current(current),
        current_isValid(current_isValid),
        controlMode(controlMode),
        controlMode_isValid(controlMode_isValid),
        interactionMode(interactionMode),
        interactionMode_isValid(interactionMode_isValid)
{
}


} // namespace yarp::dev::impl
